set(DMK_TEST_SRC test_all.cpp test_pbc_periodic.cpp test_direct.cpp test_esp.cpp test_yukawa_levels.cpp)
if (DMK_GPU_OFFLOAD)
  list(APPEND DMK_TEST_SRC test_gpu_parity.cpp)
endif()
if (DMK_BUILD_REFERENCE)
  list(APPEND DMK_TEST_SRC test_reference.cpp)
endif()

add_executable(test_all ${DMK_TEST_SRC})
target_link_libraries(test_all PRIVATE dmk_shared)
if (DMK_GPU_OFFLOAD)
  target_link_libraries(test_all PRIVATE ${DMK_GPU_TARGET})
endif()
if (DMK_BUILD_REFERENCE)
  target_link_libraries(test_all PRIVATE dmk_ref)
endif()
