#pragma once

// Device K0/K1 for the free-space 2D Yukawa direct kernel.
//
// NVRTC provides no standard headers, so this cannot be include/dmk/bessel.hpp: no <cmath>, no
// std::, and no std::is_same_v. The x <= 0 -> NaN guard is dropped because the caller masks
// R2 == 0. __device__ is explicit so the file also compiles under plain nvcc.
//
// The rational approximations and their coefficient tables are copied verbatim from
// include/dmk/bessel.hpp (generated by scripts/gen_bessel.py from JuliaMath/Bessels.jl, MIT,
// commit 009b615). If a Bessels.jl bump changes those tables, change these to match.

namespace dmk::cuda::bessel {
namespace detail {

template <class A, class B>
constexpr bool bsame = false;
template <class A>
constexpr bool bsame<A, A> = true;

// Horner evaluation of a polynomial with ascending coefficients.
template <class T, int N>
__device__ inline T evalpoly(T x, const T (&c)[N]) {
    T r = c[N - 1];
    for (int i = N - 1; i-- > 0;)
        r = fma(r, x, c[i]);
    return r;
}

} // namespace detail

template <class T>
__device__ inline T k0(T x) {
    using namespace detail;
    if constexpr (bsame<T, double>) {
        if (x <= 1.0) {
            constexpr double P1_k0_d[5] = {-0.13725090026855463, 0.2574916117833313, 0.013954746021468694,
                                           0.0005445476986653927, 7.125159422136622e-06};
            constexpr double Q1_k0_d[4] = {1.0, -0.054583334380177886, 0.0012910528169752513, -1.3676539469785865e-05};
            constexpr double P2_k0_d[8] = {0.11593151565841245,   0.27898287891460316,    0.02524892993216122,
                                           0.0008460350907213638, 1.4914719243096176e-05, 1.6271068924220885e-07,
                                           1.208266102392756e-09, 6.611686391749704e-12};
            constexpr double Y_k0_d = 1.1372509002685547;
            double a = x * x / 4;
            double s = evalpoly(a, P1_k0_d) / evalpoly(a, Q1_k0_d) + Y_k0_d;
            a = fma(s, a, 1.0);
            return fma(-a, log(x), evalpoly(x * x, P2_k0_d));
        } else {
            constexpr double P3_k0_d[9] = {0.25331413731550023, 3.6283421339845954,  18.68441889406606,
                                           43.062439810634125,  44.24116209627428,   15.620953393562205,
                                           -1.8101389782294108, -1.4142379942699959, -0.09369168119754924};
            constexpr double Q3_k0_d[9] = {1.0,
                                           14.941946948799083,
                                           82.65296455388554,
                                           216.2779506621867,
                                           284.51451551842223,
                                           185.1714491916335,
                                           54.865407174397234,
                                           6.1180758376289575,
                                           0.1586261269326235};
            double s = exp(-x / 2);
            double a = (evalpoly(1.0 / x, P3_k0_d) / evalpoly(1.0 / x, Q3_k0_d) + 1.0) * s / sqrt(x);
            return a * s;
        }
    } else {
        if (x <= 1.0f) {
            constexpr float P1_k0_f[3] = {-0.13725089791042597f, 0.2622545986273688f, 0.00504710372824792f};
            constexpr float Q1_k0_f[3] = {1.0f, -0.08928694018000029f, 0.0029859806841809693f};
            constexpr float P2_k0_f[5] = {0.1159315158f, 0.2789828686f, 0.02524902861f, 0.0008457241514f,
                                          1.530051997e-05f};
            constexpr float Y_k0_f = 1.1372509002685547f;
            float a = x * x / 4;
            float s = evalpoly(a, P1_k0_f) / evalpoly(a, Q1_k0_f) + Y_k0_f;
            a = fma(s, a, 1.0f);
            return fma(-a, log(x), evalpoly(x * x, P2_k0_f));
        } else {
            constexpr float P3_k0_f[4] = {0.253314122f, 0.5221502603f, 0.06380180669f, -0.05934976547f};
            constexpr float Q3_k0_f[4] = {1.0f, 2.679722431f, 1.561635813f, 0.1573660661f};
            float s = exp(-x / 2);
            float a = (evalpoly(1.0f / x, P3_k0_f) / evalpoly(1.0f / x, Q3_k0_f) + 1.0f) * s / sqrt(x);
            return a * s;
        }
    }
}

template <class T>
__device__ inline T k1(T x) {
    using namespace detail;
    if constexpr (bsame<T, double>) {
        if (x <= 1.0) {
            constexpr double P1_k1_d[4] = {-0.0036213795344035024, 0.007118420874903303, 1.003025602566143e-05,
                                           1.7723108538104081e-06};
            constexpr double Q1_k1_d[4] = {1.0, -0.048041479442904385, 0.0009859726419344165, -8.911968593970703e-06};
            constexpr double P2_k1_d[4] = {-0.3079657578292062, -0.07809297036730749, -0.0027061934375405164,
                                           -2.4954952222907202e-05};
            constexpr double Q2_k1_d[4] = {1.0, -0.02363168364121631, 0.00026452457752596274, -1.4974961800416278e-06};
            constexpr double Y_k1_d = 0.08695471286773682;
            double z = x * x, a = z / 4;
            double pq = evalpoly(a, P1_k1_d) / evalpoly(a, Q1_k1_d) + Y_k1_d;
            pq = fma(pq * a, a, (a / 2 + 1));
            double aa = pq * x / 2;
            pq = fma(evalpoly(z, P2_k1_d) / evalpoly(z, Q2_k1_d), x, 1.0 / x);
            return fma(aa, log(x), pq);
        } else {
            constexpr double P3_k1_d[9] = {-0.1970280410292263, -2.3240896154808763, -7.982697845076999,
                                           -2.399684107742216,  32.83140437808587,   56.771376115849606,
                                           33.090778846650984,  6.625822889337398,   0.3088518406452867};
            constexpr double Q3_k1_d[9] = {1.0,
                                           14.181140929882611,
                                           73.59794663175565,
                                           177.82179393708086,
                                           211.01450159870598,
                                           119.42526295106445,
                                           28.84480643024476,
                                           2.2791292710413975,
                                           0.025035818695347867};
            constexpr double Y2_k1_d = 1.4503421783447266;
            double s = exp(-x / 2);
            double a = (evalpoly(1.0 / x, P3_k1_d) / evalpoly(1.0 / x, Q3_k1_d) + Y2_k1_d) * s / sqrt(x);
            return a * s;
        }
    } else {
        if (x <= 1.0f) {
            constexpr float P1_k1_f[3] = {-0.003621379531f, 0.007131781976f, -1.5352783e-05f};
            constexpr float Q1_k1_f[3] = {1.0f, -0.05173102701f, 0.0009203530671f};
            constexpr float P2_k1_f[4] = {-0.3079657469f, -0.08537108913f, -0.004640275408f, -0.0001156442414f};
            constexpr float Q2_k1_f[2] = {1.0f, 0.0f};
            constexpr float Y_k1_f = 0.08695471287f;
            float z = x * x, a = z / 4;
            float pq = evalpoly(a, P1_k1_f) / evalpoly(a, Q1_k1_f) + Y_k1_f;
            pq = fma(pq * a, a, (a / 2 + 1));
            float aa = pq * x / 2;
            pq = fma(evalpoly(z, P2_k1_f) / evalpoly(z, Q2_k1_f), x, 1.0f / x);
            return fma(aa, log(x), pq);
        } else {
            constexpr float P3_k1_f[4] = {-0.1970280088f, 0.02188747807f, 0.7270394756f, 0.2490678196f};
            constexpr float Q3_k1_f[4] = {1.0f, 2.274292882f, 0.9904984851f, 0.04585534549f};
            constexpr float Y2_k1_f = 1.450342178f;
            float s = exp(-x / 2);
            float a = (evalpoly(1.0f / x, P3_k1_f) / evalpoly(1.0f / x, Q3_k1_f) + Y2_k1_f) * s / sqrt(x);
            return a * s;
        }
    }
}

} // namespace dmk::cuda::bessel
