#ifndef DMK_CUDA_DIRECT_KERNELS_HPP
#define DMK_CUDA_DIRECT_KERNELS_HPP

// Per-box direct evaluator. launch_direct_by_box_dispatch dispatches on
// (kernel, dim, n_digits) against the AOT instantiation table in
// src/cuda/aot_kernels.cu (generated by scripts/generate_aot_kernels).

#include <dmk.h>

#include <cuda_runtime.h>
#include <dmk/cuda/direct_kernelargs.hpp>
namespace dmk::cuda {

template <typename Real>
void launch_direct_by_box_dispatch(dmk_ikernel kernel, int dim, int n_digits, const DirectByBoxArgs<Real> &args,
                                   cudaStream_t stream);

} // namespace dmk::cuda

#endif // DMK_CUDA_DIRECT_KERNELS_HPP
