// Auto-generated by generate_aot_kernels. Do not edit.
// Unit: laplace_3d
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>
#include <utility>
#include <vector>

namespace dmk {
constexpr int unroll_factor = 3;

// beta: 5.634
constexpr double laplace_3d_potential_2[] = {2.25282002582155055e-01, -4.99920725695796930e-01, 2.81210802686322481e-01,
                                             -1.03887468188636439e-03};

// beta: 8.298
constexpr double laplace_3d_potential_3[] = {1.35676693383068231e-01,  -4.22679758881918444e-01,
                                             4.46694841556203426e-01,  -1.21102947058209454e-01,
                                             -8.26625453105883506e-02, 4.40644298701292625e-02};

// beta: 10.962
constexpr double laplace_3d_potential_4[] = {
    8.61916042476558453e-02,  -3.39357689807749219e-01, 4.95769318253879487e-01,  -2.63353000669118043e-01,
    -7.92301496463873600e-02, 1.25856582628138036e-01,  -2.76665730002910318e-03, -2.31735239043814184e-02};

// beta: 13.626000000000001
constexpr double laplace_3d_potential_5[] = {
    5.58390435893019663e-02, -2.64586084955049261e-01, 4.87356384393162034e-01,  -3.84994597954706641e-01,
    1.16315189240913750e-02, 1.85666658452653177e-01,  -8.23628275754923894e-02, -3.98393432987490456e-02,
    3.31102704081132765e-02, 3.75332824122639758e-03,  -5.57532476536800898e-03};

// beta: 16.29
constexpr double laplace_3d_potential_6[] = {
    3.65651153834013268e-02, -2.02373828741634704e-01, 4.50680962873918789e-01,  -4.71259094659650657e-01,
    1.31151290530008124e-01, 1.97006325911610741e-01,  -1.75941155471667859e-01, -1.49657566484197244e-02,
    7.23405502287229746e-02, -1.16581017499437639e-02, -1.68036765809427453e-02, 3.25068552699544610e-03,
    2.00696867284461816e-03};

// beta: 18.954
constexpr double laplace_3d_potential_7[] = {
    2.41435731559801123e-02, -1.52729533229260889e-01, 3.98895426171370859e-01,  -5.19059925199433780e-01,
    2.61759703204077210e-01, 1.53278369473923204e-01,  -2.67097148186365596e-01, 5.99652945526592748e-02,
    1.00000753621406493e-01, -5.88930498174368017e-02, -1.92963638496512387e-02, 2.06712499977083665e-02,
    1.59403688932523418e-03, -3.23248151527584038e-03};

// beta: 21.618000000000002
constexpr double laplace_3d_potential_8[] = {
    1.60439437296675640e-02,  -1.14126073550636378e-01, 3.41987337192511121e-01,  -5.32522731286782625e-01,
    3.82845035891724916e-01,  6.19184951923090338e-02,  -3.28185447928564689e-01, 1.72307149780891899e-01,
    8.96059941698951201e-02,  -1.23461528598353215e-01, 7.59229237815524285e-03,  4.44741945776204600e-02,
    -1.41898651813544500e-02, -9.64407308797441548e-03, 5.05118678882309890e-03,  1.05456872216903733e-03,
    -7.50479469805201546e-04};

// beta: 24.282
constexpr double laplace_3d_potential_9[] = {
    1.07159462374928523e-02,  -8.46341160946152277e-02, 2.86172402632982548e-01,  -5.18876415012229586e-01,
    4.81152338514268363e-01,  -6.26555153882026178e-02, -3.41806798659518574e-01, 3.02197463492700547e-01,
    2.78618128968503437e-02,  -1.84360855208628632e-01, 6.88980134368040315e-02,  5.65882082276001064e-02,
    -4.62859517784542374e-02, -8.22864098552431034e-03, 1.65706697984436407e-02,  -2.45712876778660994e-04,
    -3.69762826634758429e-03, 2.15584244995764644e-04,  4.19195434991927001e-04};

// beta: 26.946
constexpr double laplace_3d_potential_10[] = {
    7.18708237059719791e-03,  -6.23865646673537194e-02, 2.34945455950023613e-01,  -4.86161809063531958e-01,
    5.50172803263395238e-01,  -2.02350858567595993e-01, -3.00904600453594573e-01, 4.23072285773979484e-01,
    -8.85142719163944380e-02, -2.14363943722174016e-01, 1.62465545958938223e-01,  3.54600844428899428e-02,
    -8.91198361553773438e-02, 1.61613561954918085e-02,  2.92803322475974834e-02,  -1.34235174701271848e-02,
    -6.29553570621151776e-03, 4.98393641198560753e-03,  8.34446597239230591e-04,  -1.11398751569548641e-03,
    -5.14221535104267654e-05, 1.23018192605541074e-04};

// beta: 29.610000000000003
constexpr double laplace_3d_potential_11[] = {
    4.83699369429514345e-03,  -4.57629949245662096e-02, 1.89944134896976174e-01,  -4.41694820807374988e-01,
    5.88938808524209989e-01,  -3.40295394858704248e-01, -2.09484233544280640e-01, 5.10379535704030496e-01,
    -2.47274179951901069e-01, -1.90310301964979833e-01, 2.70493212718880660e-01,  -3.20750547444539069e-02,
    -1.25666115771994574e-01, 6.59722816074232998e-02,  3.09799838816447737e-02,  -3.60662789129123224e-02,
    -1.52631851038950955e-03, 1.24019732330262217e-02,  -1.83565084760144506e-03, -2.99799802313175561e-03,
    6.85379511706281038e-04,  4.91463901760632997e-04,  -9.20146044351580157e-05, -4.24102106538326771e-05};

// beta: 32.274
constexpr double laplace_3d_potential_12[] = {
    3.26488932883790091e-03,  -3.34334184769561060e-02, 1.51628119161831165e-01,  -3.91438301385976573e-01,
    6.00144886697036140e-01,  -4.63260754695098143e-01, -7.91094654958735960e-02, 5.46372213823562269e-01,
    -4.25336253533089070e-01, -9.77574303076449019e-02, 3.64039081784227669e-01,  -1.51925312083628056e-01,
    -1.30807301807728871e-01, 1.40036061648695781e-01,  5.66849557035009957e-03,  -6.42865124364210422e-02,
    1.86967051122529301e-02,  1.88572407480448352e-02,  -1.12662015297383296e-02, -3.44125699098016269e-03,
    3.78038404248679481e-03,  2.39078119218961082e-04,  -7.82727229555982935e-04, 4.93023050799382170e-05,
    7.93878994049295519e-05,  -1.09102680236039761e-05};

// beta: 8.298
constexpr double laplace_3d_potential_grad_2[] = {1.35373393795720692e-01, -4.36907496688934471e-01,
                                                  4.49104115534396831e-01, -6.54190101699606286e-02,
                                                  -8.50658566475083061e-02};

// beta: 10.962
constexpr double laplace_3d_potential_grad_3[] = {8.60612156248130727e-02,  -3.40111927203895936e-01,
                                                  4.97659587015112592e-01,  -2.50082439360021058e-01,
                                                  -8.37086507244033384e-02, 9.08624864724610626e-02};

// beta: 13.626000000000001
constexpr double laplace_3d_potential_grad_4[] = {
    5.58390435893020218e-02,  -2.64717167590847735e-01, 4.87559575065030892e-01,
    -3.83241492306865494e-01, 8.96132752589977148e-03,  1.79344646567271587e-01,
    -7.28417849593808592e-02, -3.14007565336095265e-02, 2.05017147121834692e-02};

// beta: 16.29
constexpr double laplace_3d_potential_grad_5[] = {
    3.65651153834012990e-02, -2.02336522120227985e-01, 4.50703044165623401e-01,  -4.71988793396330319e-01,
    1.30713175727858899e-01, 2.01028804034472791e-01,  -1.73501647366733819e-01, -2.40526631146708372e-02,
    6.67882926557134132e-02, -2.65352836539563090e-03, -1.12698283550172283e-02};

// beta: 18.954
constexpr double laplace_3d_potential_grad_6[] = {
    2.41435365819562368e-02, -1.52718808764497921e-01, 3.98897944342020083e-01,  -5.19356388662591928e-01,
    2.61731244800182006e-01, 1.55627597162875442e-01,  -2.66978590303516672e-01, 5.19699102108855393e-02,
    9.97763197131621704e-02, -4.56454000595140560e-02, -1.90998195412067882e-02, 1.01237641756432902e-02,
    1.52931819491995431e-03};

// beta: 21.618000000000002
constexpr double laplace_3d_potential_grad_7[] = {
    1.60439680211329795e-02,  -1.14126099610511914e-01, 3.41984271196447198e-01,  -5.32521756854699824e-01,
    3.82908730215659632e-01,  6.19079603329049238e-02,  -3.28690650132687112e-01, 1.72357352569426858e-01,
    9.15769080873981428e-02,  -1.23584312439697891e-01, 3.41197217941373396e-03,  4.46349951564157174e-02,
    -9.27357818320668700e-03, -9.75130738557921685e-03, 2.03839781997119636e-03,  1.08317173001665928e-03};

// beta: 24.282
constexpr double laplace_3d_potential_grad_8[] = {
    1.07159462374928523e-02,  -8.46341793364562833e-02, 2.86172289845876782e-01,  -5.18873461702700878e-01,
    4.81157708128312989e-01,  -6.26959661442080818e-02, -3.41881484578489769e-01, 3.02447220896404911e-01,
    2.83287777506400426e-02,  -1.85181087225704200e-01, 6.73483269472894552e-02,  5.81198065641782002e-02,
    -4.33665484079018421e-02, -9.86037397693287181e-03, 1.34367184014683710e-02,  6.78038463523805333e-04,
    -1.91174021845368926e-03};

// beta: 26.946
constexpr double laplace_3d_potential_grad_9[] = {
    7.18708246440367265e-03,  -6.23865649137638756e-02, 2.34945437005272401e-01,  -4.86161760244670338e-01,
    5.50173433125147771e-01,  -2.02352457277721304e-01, -3.00912710492949653e-01, 4.23092619570351436e-01,
    -8.84613031406586287e-02, -2.14495407348589684e-01, 1.62267009118026828e-01,  3.59486417552733750e-02,
    -8.86671064485698157e-02, 1.50553796593915507e-02,  2.86417091603183814e-02,  -1.18732171211611646e-02,
    -5.75137033229802461e-03, 3.67017900763767562e-03,  5.77819645270764371e-04,  -4.97413300023614720e-04};

// beta: 29.610000000000003
constexpr double laplace_3d_potential_grad_10[] = {
    4.83699364701164342e-03,  -4.57629949453203164e-02, 1.89944146189103547e-01,  -4.41694815805404428e-01,
    5.88938361753583606e-01,  -3.40295594190500927e-01, -2.09477327720605233e-01, 5.10382635298455400e-01,
    -2.47328995077170849e-01, -1.90335030062067756e-01, 2.70747291815721935e-01,  -3.19599348895081709e-02,
    -1.26400907973926058e-01, 6.56380950546598396e-02,  3.23455685814820898e-02,  -3.54431405368228966e-02,
    -3.15749917183956626e-03, 1.16554507911594430e-02,  -6.25242294921542078e-04, -2.44259444406770901e-03,
    1.77610289495549849e-04,  2.57923748564379933e-04};

// beta: 32.274
constexpr double laplace_3d_potential_grad_11[] = {
    3.26488932935758936e-03,  -3.34334184589342026e-02, 1.51628119013288543e-01,  -3.91438303230557672e-01,
    6.00144893739365637e-01,  -4.63260698656872971e-01, -7.91095963485347747e-02, 5.46371422708288978e-01,
    -4.25334996766092766e-01, -9.77511664059468321e-02, 3.64031957093882585e-01,  -1.51956009896253158e-01,
    -1.30781688719692979e-01, 1.40134444080656562e-01,  5.60786571449403779e-03,  -6.44986132385584748e-02,
    1.87924679144229438e-02,  1.91671466716092885e-02,  -1.13661256210334030e-02, -3.74395560480559296e-03,
    3.84651785292284892e-03,  4.28341104036052773e-04,  -8.07875592590791974e-04, -1.91890722053818430e-05,
    8.35723911323348051e-05};

// beta: 34.938
constexpr double laplace_3d_potential_grad_12[] = {
    2.20928059493365235e-03,  -2.43426875242211231e-02, 1.19761893706071723e-01,  -3.39856659040368825e-01,
    5.88505140797872417e-01,  -5.62618110858054132e-01, 7.48570909907567972e-02,  5.22999143696575630e-01,
    -5.95015655106605257e-01, 6.28415423705892401e-02,  4.10829665279586365e-01,  -3.12678103311007982e-01,
    -7.88556227096840062e-02, 2.21754901069865118e-01,  -6.05635485305918708e-02, -8.38912139235251930e-02,
    5.89552927275863239e-02,  1.58589038944522143e-02,  -2.78508907904069791e-02, 1.30941825171451503e-03,
    8.91950669951599787e-03,  -1.86784537729052513e-03, -2.04171779144781936e-03, 5.57931216423200984e-04,
    3.14659759362786421e-04,  -6.72204654220478630e-05, -2.50956269826985266e-05};

template <class Real, int MaxVecLen>
residual_evaluator_func<Real> get_laplace_3d_kernel(dmk_eval_type eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (eval_level == DMK_POTENTIAL) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 4;
            constexpr int NC0 = 4;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 6;
            constexpr int NC0 = 6;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 8;
            constexpr int NC0 = 8;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 11;
            constexpr int NC0 = 11;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 13;
            constexpr int NC0 = 13;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 14;
            constexpr int NC0 = 14;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 17;
            constexpr int NC0 = 17;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 19;
            constexpr int NC0 = 19;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 22;
            constexpr int NC0 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 24;
            constexpr int NC0 = 24;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 26;
            constexpr int NC0 = 26;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    } else if (eval_level == DMK_POTENTIAL_GRAD) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 5;
            constexpr int NC0 = 5;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 6;
            constexpr int NC0 = 6;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 9;
            constexpr int NC0 = 9;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 11;
            constexpr int NC0 = 11;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 13;
            constexpr int NC0 = 13;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 16;
            constexpr int NC0 = 16;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 17;
            constexpr int NC0 = 17;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 20;
            constexpr int NC0 = 20;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 22;
            constexpr int NC0 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 25;
            constexpr int NC0 = 25;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 27;
            constexpr int NC0 = 27;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_3d_potential_grad_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    }
    throw std::runtime_error("Unsupported eval_level/n_digits combination");
}

// Explicit instantiations
template residual_evaluator_func<float> get_laplace_3d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_eval_type, int);
template residual_evaluator_func<double> get_laplace_3d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_eval_type,
                                                                                                      int);

} // namespace dmk
