// Auto-generated by generate_aot_kernels. Do not edit.
// Unit: esp_stokeslet_3d_ranges
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>
#include <utility>
#include <vector>

namespace dmk {
constexpr int unroll_factor = 3;

// beta: 0
constexpr double esp_stokeslet_3d_velocity_2[] = {
    -1.45330168077935418e-01, -4.02561489357531471e-02, 5.00781940028783623e-01,  -2.18252701054278853e-01,
    -1.07900009948411202e-01, 2.91524541564167072e-01,  -4.08581057100382172e-01, -6.48839672128554146e-02,
    1.65139179001566438e-01,  2.51798823541386392e-02};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_3[] = {
    -1.35117598279079876e-01, 1.09823600977811256e-01,  4.21237114742523955e-01,  -5.90649651555818833e-01,
    -9.10881503594436330e-04, 2.86895083348190971e-01,  -3.56906167615126391e-02, -5.64950888486494551e-02,
    2.38975547558487211e-01,  -4.79348710924276278e-01, 6.57198657043774614e-02,  3.50003624332287433e-01,
    -9.88567317360971171e-02, -1.20821076230939836e-01, 4.47737895732901875e-02};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_4[] = {
    -1.02998242771318083e-01, 2.25538691712745792e-01,  1.43989708138149958e-01,  -7.46924581142423993e-01,
    4.92152412067750400e-01,  3.03009492152616022e-01,  -3.77166893204392673e-01, -2.16366565946393558e-02,
    9.40651705695215445e-02,  -1.00052430259784681e-02, 1.57316648584176988e-01,  -4.85747471983049794e-01,
    3.42350781388136627e-01,  3.55186209789876584e-01,  -4.78467207074801726e-01, -1.14881591266974906e-01,
    3.02601574854770738e-01,  -1.81108277818025146e-02, -7.38339047804456722e-02, 1.35716787648408211e-02};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_5[] = {
    -8.68765844459773451e-02, 2.45935476013306925e-01,  2.98971559351797174e-03,  -7.02283993299189557e-01,
    7.59197162537268322e-01,  1.25399480157157489e-01,  -6.12373862421075610e-01, 1.67081496845167349e-01,
    2.23604877478071895e-01,  -1.10039432069176782e-01, -3.65458715728510450e-02, 2.39083149932594261e-02,
    1.26535139223097226e-01,  -4.59341417399685092e-01, 4.56416507770840973e-01,  2.44755913400802466e-01,
    -6.53511027925004262e-01, 7.32346282603155152e-02,  4.58350843399149555e-01,  -1.89483905951682019e-01,
    -1.64595615764232983e-01, 1.02178058283854664e-01,  2.68079413999300041e-02,  -2.13442018576410833e-02};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_6[] = {
    -7.22790838728191165e-02, 2.49742022702694050e-01,  -1.18040155819408840e-01, -5.98346552895317241e-01,
    9.55628876691553386e-01,  -1.45839849937107302e-01, -7.22716305486585942e-01, 4.46109891136227621e-01,
    2.42442393416013979e-01,  -2.78931113700176814e-01, -3.55880790190828133e-02, 9.14139103503797262e-02,
    5.51851268983808980e-04,  -1.41489297023000907e-02, 1.01367982602032669e-01,  -4.23389676395730830e-01,
    5.41430460206661968e-01,  9.62788655208145772e-02,  -7.52735762975043077e-01, 3.25072107347094519e-01,
    4.94838422678293699e-01,  -4.24295643211262508e-01, -1.52546240363086033e-01, 2.42207524038145383e-01,
    1.61496209207082769e-02,  -7.78881716296915549e-02, 1.49603344103104992e-03,  1.20155653820326613e-02};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_7[] = {
    -4.85810761211917796e-02, 2.27061647214790802e-01,  -2.88613466296047172e-01, -2.91687767509671847e-01,
    1.11183626355490794e+00,  -8.14177075070700140e-01, -5.35058909441032515e-01, 1.06035627136248101e+00,
    -1.68559879779971999e-01, -5.84344514111508229e-01, 2.99540380491454372e-01,  1.82584720269397927e-01,
    -1.62134956121299245e-01, -3.22890936379820401e-02, 4.84196179945188127e-02,  2.49580069597767204e-03,
    -6.84800161053422066e-03, 6.44054708301615708e-02,  -3.40048165776445033e-01, 6.28661774608792578e-01,
    -2.40770638252217090e-01, -7.25224652654012036e-01, 8.72312980865794896e-01,  2.05553422664869478e-01,
    -8.83793026385699010e-01, 2.56997829400001820e-01,  4.58639263525761010e-01,  -2.90519382547901439e-01,
    -1.37445148130330930e-01, 1.47210721723035759e-01,  2.25401328895335068e-02,  -4.31522473198324222e-02,
    -1.43538619706511691e-03, 6.06708814259779294e-03};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_8[] = {
    -3.94060647227535421e-02, 2.07804892591352902e-01,  -3.38283309939463706e-01, -1.24543297727807867e-01,
    1.07187018937736123e+00,  -1.12892347923220893e+00, -2.46856921026415294e-01, 1.27848344687706539e+00,
    -5.65095740670132018e-01, -6.02827631223275984e-01, 5.90209432112017374e-01,  1.10351516628452245e-01,
    -3.03762042978786673e-01, 2.49212153049918408e-02,  1.00566591817998874e-01,  -1.86990433118731543e-02,
    -2.16357172473477140e-02, 3.43238333601580655e-03,  2.39358366286809366e-03,  5.11292227639069674e-02,
    -2.98340186642652216e-01, 6.36623587184168116e-01,  -3.99318776782193963e-01, -6.10282153313895348e-01,
    1.09607609307319143e+00,  -9.65792045746942107e-02, -1.00551699938332617e+00, 6.11626030819647504e-01,
    4.30451398591817136e-01,  -5.38042374433874926e-01, -5.45111663573235386e-02, 2.65712106321734032e-01,
    -3.46909900362110529e-02, -8.66444779608876170e-02, 1.91919913066799924e-02,  1.84908325375043835e-02,
    -3.34136676198408750e-03, -2.03356951553153222e-03};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_9[] = {
    -2.55389817834970057e-02, 1.64986776104815741e-01,  -3.79287408051037667e-01, 1.75539754643736667e-01,
    8.09916708538945374e-01,  -1.56215046471226171e+00, 5.89828549412836911e-01,  1.29324888484936285e+00,
    -1.53413026521247819e+00, -1.19285123821474062e-01, 1.17361764254831735e+00,  -4.62862839029407336e-01,
    -4.82206911915685266e-01, 4.01804149914476272e-01,  1.02763451489586100e-01,  -1.90424341766742750e-01,
    -1.73883874483230432e-04, 6.03777946267899934e-02,  -5.95026224982889238e-03, -1.25666528114293883e-02,
    1.16136129096078614e-03,  1.33206208955337206e-03,  3.20171347291570152e-02,  -2.22542892091093264e-01,
    6.01830303140966749e-01,  -6.50940959908270833e-01, -2.46745753272201912e-01, 1.32294700857178049e+00,
    -8.71339832321877061e-01, -8.43223171633317503e-01, 1.40739945757869500e+00,  -9.48585910741818750e-02,
    -9.83247512606144514e-01, 4.85736845741554790e-01,  3.81939699025557189e-01,  -3.75435152423082119e-01,
    -7.12550111650920998e-02, 1.72247107531754651e-01,  -6.03575085084342034e-03, -5.38955505883771877e-02,
    6.61938197129546737e-03,  1.11414216522547124e-02,  -1.18211641481926876e-03, -1.17606585311597436e-03};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_10[] = {
    -2.04384090066388469e-02, 1.44072221025614899e-01,  -3.77586693770008475e-01, 2.95064921148863069e-01,
    6.20534092848069929e-01,  -1.64956729593177065e+00, 1.05560730561509897e+00,  1.05071912014691926e+00,
    -1.97127364019937334e+00, 4.03916533554575907e-01,  1.31192388056495024e+00,  -9.48229287112095531e-01,
    -3.88144820130259638e-01, 6.77215903681530285e-01,  -3.70070974357352075e-02, -2.95881262595688199e-01,
    9.02855978781445107e-02,  8.88813853591309544e-02,  -4.39878731156773742e-02, -1.84838780580627166e-02,
    1.14588819670327184e-02,  2.44710404284200628e-03,  -1.37122525764388778e-03, -1.55465263746289677e-04,
    2.52678189679327869e-02,  -1.89778448909329323e-01, 5.67365143719162246e-01,  -7.36567841540866297e-01,
    -3.14987612085671775e-02, 1.30874580617148450e+00,  -1.26464066403055786e+00, -5.40086116787813819e-01,
    1.72331160226701008e+00,  -5.93999105039683117e-01, -1.04100799747092787e+00, 9.15779335730488531e-01,
    2.62376670150980873e-01,  -6.10991227234983225e-01, 6.79536422608677249e-02,  2.59708117093241098e-01,
    -9.17710211512029611e-02, -7.64484273167567729e-02, 4.21337063668163689e-02,  1.54798172136885702e-02,
    -1.07687923641252917e-02, -1.95493067759875370e-03, 1.27865253176690473e-03,  1.13021299502640883e-04};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_11[] = {
    -1.29713756739019415e-02, 1.06632427936200411e-01,  -3.46331841063612700e-01, 4.61628821080934004e-01,
    2.04551073040647180e-01,  -1.56275011827907528e+00, 1.87851587213689308e+00,  1.25618309617478358e-01,
    -2.42192545620370403e+00, 1.83762845965806165e+00,  9.23462315986234072e-01,  -2.04400705432847563e+00,
    4.32938829087462118e-01,  1.11696864455789990e+00,  -7.26757564997034700e-01, -3.22116767668577275e-01,
    4.63784743744248495e-01,  4.46493790660573361e-03,  -1.90270104005864832e-01, 4.26878187982654977e-02,
    5.41735751661287721e-02,  -2.16642457704927967e-02, -1.01219512968544825e-02, 5.55079321509482481e-03,
    9.51884083335958640e-04,  -6.42026728735983093e-04, 1.56678744444360141e-02,  -1.35271678046394062e-01,
    4.81603519336896768e-01,  -8.27788394242883974e-01, 3.92422898495839723e-01,  1.04759660199941451e+00,
    -1.88427880444767371e+00, 4.16863071616383696e-01,  1.91084580970450735e+00,  -1.86475149897253045e+00,
    -5.28794849428510516e-01, 1.81722714440295996e+00,  -5.46906230002338511e-01, -9.36347866310586974e-01,
    7.05930099981114112e-01,  2.45940355822564294e-01,  -4.28315063243543681e-01, 1.47794805291696033e-02,
    1.72115574676396266e-01,  -4.47101762643978343e-02, -4.84215291815941196e-02, 2.11648554019119410e-02,
    8.96798594136317788e-03,  -5.31089717636047329e-03, -8.37286280268241686e-04, 6.09001245288428097e-04};

// beta: 0
constexpr double esp_stokeslet_3d_velocity_12[] = {
    -1.02949470535727006e-02, 9.06357558182818018e-02,  -3.22251664181469333e-01, 5.10105117151201215e-01,
    3.51673821367180783e-03,  -1.40871142116777648e+00, 2.17437784760166597e+00,  -4.84524736441024950e-01,
    -2.34816963042997706e+00, 2.60170480443309682e+00,  3.23793042824442823e-01,  -2.45798526485808022e+00,
    1.18311225137647780e+00,  1.09315779756170284e+00,  -1.25177128980511454e+00, -1.07932682244523959e-01,
    7.02343836056771198e-01,  -1.85049612720302320e-01, -2.60978337845894637e-01, 1.47711805300286880e-01,
    6.60437689089072438e-02,  -6.51331523850651184e-02, -1.04816444712558261e-02, 1.94183735904337462e-02,
    7.41125545462553628e-04,  -3.75826891618937300e-03, 1.89032602673012395e-05,  3.61484878460096681e-04,
    1.23138887271507236e-02,  -1.13244591600100336e-01, 4.35496255782633568e-01,  -8.38184151408877365e-01,
    5.79614854615742914e-01,  8.26986518957383510e-01,  -2.06222342045085094e+00, 9.93621200325024656e-01,
    1.71794201702203253e+00,  -2.49329338936809464e+00, 8.81361083661525574e-02,  2.10493181336644231e+00,
    -1.23972042281791661e+00, -8.54548757758811561e-01, 1.16931684160658111e+00,  2.35277575544764611e-02,
    -6.31400252279186169e-01, 1.96654626002729593e-01,  2.28754194692605467e-01,  -1.42856549938671029e-01,
    -5.60510947178592886e-02, 6.13409534844171420e-02,  8.28395272231670018e-03,  -1.80814574129800204e-02,
    -4.20067664214398260e-04, 3.47967658532472024e-03,  -4.28556055798588644e-05, -3.33648788706084954e-04};

template <class Real, int MaxVecLen>
residual_evaluator_range_func<Real> get_esp_stokeslet_3d_kernel_ranges(dmk_eval_type eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (eval_level == DMK_VELOCITY) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 10;
            constexpr int NC0 = 5;
            constexpr int NC1 = 5;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 15;
            constexpr int NC0 = 8;
            constexpr int NC1 = 7;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 20;
            constexpr int NC0 = 10;
            constexpr int NC1 = 10;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 24;
            constexpr int NC0 = 12;
            constexpr int NC1 = 12;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 28;
            constexpr int NC0 = 14;
            constexpr int NC1 = 14;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 34;
            constexpr int NC0 = 17;
            constexpr int NC1 = 17;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 38;
            constexpr int NC0 = 19;
            constexpr int NC1 = 19;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 44;
            constexpr int NC0 = 22;
            constexpr int NC1 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 48;
            constexpr int NC0 = 24;
            constexpr int NC1 = 24;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 52;
            constexpr int NC0 = 26;
            constexpr int NC1 = 26;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 56;
            constexpr int NC0 = 28;
            constexpr int NC1 = 28;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_stokeslet_3d_velocity_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_ranges, const int *range_starts, const int *range_lens, int n_trg,
                       const Real *r_trg, Real *pot, const Real *q_trg, Real *pot_src) {
                stokeslet_3d_poly_all_pairs_ranges<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_ranges, range_starts,
                    range_lens, n_src, r_src, charge, normals, n_trg, r_trg, pot, q_trg, pot_src, UF);
            };
        }
    }
    throw std::runtime_error("Unsupported eval_level/n_digits combination");
}

// Explicit instantiations
template residual_evaluator_range_func<float>
get_esp_stokeslet_3d_kernel_ranges<float, sctl::DefaultVecLen<float>()>(dmk_eval_type, int);
template residual_evaluator_range_func<double>
get_esp_stokeslet_3d_kernel_ranges<double, sctl::DefaultVecLen<double>()>(dmk_eval_type, int);

} // namespace dmk
