// Auto-generated by generate_aot_kernels. Do not edit.
// Unit: esp_laplace_2d
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>
#include <utility>
#include <vector>

namespace dmk {
constexpr int unroll_factor = 3;

// beta: 0
constexpr double esp_laplace_2d_potential_2[] = {3.31407136429506921e-01, -4.44983736810248387e-01,
                                                 1.62401433556102814e-01, -5.00058300147462609e-02};

// beta: 0
constexpr double esp_laplace_2d_potential_3[] = {3.40128947052315056e-01, -4.67350647165909405e-01,
                                                 1.82788419908278349e-01, -8.17008810764013882e-02,
                                                 2.64736698760322069e-02};

// beta: 0
constexpr double esp_laplace_2d_potential_4[] = {
    3.43425620766397488e-01, -4.83060291356886218e-01, 2.06815661724620681e-01, -9.56363975134247035e-02,
    3.95916436420770332e-02, -1.53246341597736736e-02, 4.20291361748193881e-03};

// beta: 0
constexpr double esp_laplace_2d_potential_5[] = {
    3.45791791835113105e-01,  -4.94638823701766983e-01, 2.32700982261791756e-01,
    -1.31082086812848581e-01, 7.07661487158944280e-02,  -3.32311664679305063e-02,
    1.38345849225210826e-02,  -5.79296273169795876e-03, 1.65288291026933999e-03};

// beta: 0
constexpr double esp_laplace_2d_potential_6[] = {
    3.46177360874770079e-01, -4.97005359585988293e-01, 2.39238298635452873e-01, -1.42036658203261917e-01,
    8.39478592675435148e-02, -4.50956813087812561e-02, 2.07009764054380367e-02, -8.57882208536839622e-03,
    3.73645702728076694e-03, -1.08487244360550516e-03};

// beta: 0
constexpr double esp_laplace_2d_potential_7[] = {
    3.46468682743447387e-01, -4.99060441846808478e-01, 2.45979346429547135e-01, -1.55603351771571224e-01,
    1.02798920331395538e-01, -6.51428372035875447e-02, 3.79965193211083893e-02, -1.96129938771228453e-02,
    8.51796667695034135e-03, -3.49990324444903736e-03, 1.64828520828645621e-03, -4.90244168606017959e-04};

// beta: 0
constexpr double esp_laplace_2d_potential_8[] = {
    3.46519150735571824e-01, -4.99473711075286486e-01, 2.47560863981100110e-01, -1.59404941233487224e-01,
    1.09264632049333191e-01, -7.32609399355232949e-02, 4.57677006506466630e-02, -2.59573159176157316e-02,
    1.32358357921169446e-02, -5.94709367463631261e-03, 2.26595137107045343e-03, -8.19215573556561169e-04,
    3.41489111493683585e-04, -9.24085343018617470e-05};

// beta: 0
constexpr double esp_laplace_2d_potential_9[] = {
    3.46558679524847812e-01, -4.99834850211860637e-01, 2.49119199277336473e-01, -1.63639510952304751e-01,
    1.17422312190085157e-01, -8.51767864078933484e-02, 5.95417024913368273e-02, -3.88522855705760450e-02,
    2.31844720284554856e-02, -1.25568836236085758e-02, 6.19029095450276262e-03, -2.70350276174949377e-03,
    9.89234630104329250e-04, -3.61255417262498475e-04, 1.65073323779927277e-04, -4.58897637330004399e-05};

// beta: 0
constexpr double esp_laplace_2d_potential_10[] = {
    3.46565736631153143e-01, -4.99907483838147593e-01, 2.49474193193855942e-01, -1.64738596995519460e-01,
    1.19848226786064466e-01, -8.92458933743993515e-02, 6.49454929811426884e-02, -4.47241318333999258e-02,
    2.85320317877610155e-02, -1.66399873734038341e-02, 8.80197625127055079e-03, -4.22275855139565316e-03,
    1.85005998716256332e-03, -7.24135133333572690e-04, 2.40373469830557974e-04, -7.96763180834371540e-05,
    3.31537216045767031e-05, -8.58140495277231689e-06};

// beta: 0
constexpr double esp_laplace_2d_potential_11[] = {
    3.46569438544917008e-01, -4.99948172166116755e-01, 2.49687315852250735e-01, -1.65447983870321752e-01,
    1.21536716495854458e-01, -9.23129050508442600e-02, 6.93759616154990544e-02, -4.99598244971918015e-02,
    3.37034475479549775e-02, -2.09903206500092580e-02, 1.19580563471582569e-02, -6.19612863377783617e-03,
    2.92745217434708504e-03, -1.27338936535266868e-03, 4.95558628313796392e-04, -1.61953520652763686e-04,
    5.42155727055558800e-05, -2.37106642001809648e-05, 6.22564417452058528e-06};

// beta: 0
constexpr double esp_laplace_2d_potential_12[] = {
    3.46572419186334690e-01, -4.99983734338924124e-01, 2.49890490129001885e-01, -1.66189269242562027e-01,
    1.23480378383596170e-01, -9.62211538819075368e-02, 7.56573041156004267e-02, -5.82648007363986351e-02,
    4.29282085819712375e-02, -2.97393061293908384e-02, 1.91454632870272819e-02, -1.13721975169510398e-02,
    6.20945182474741744e-03, -3.10964651516892985e-03, 1.42589296070909865e-03, -6.02154924850327325e-04,
    2.37188910790665021e-04, -8.43051474034488220e-05, 2.51246517177253442e-05, -7.86554630397245592e-06,
    3.35467646215108378e-06, -8.42728173519944100e-07};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_2[] = {3.31407136429506921e-01, -4.44983736810248387e-01,
                                                      1.62401433556102814e-01, -5.00058300147462609e-02};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_3[] = {3.40128947052315056e-01, -4.67350647165909405e-01,
                                                      1.82788419908278349e-01, -8.17008810764013882e-02,
                                                      2.64736698760322069e-02};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_4[] = {
    3.43425620766397488e-01, -4.83060291356886218e-01, 2.06815661724620681e-01, -9.56363975134247035e-02,
    3.95916436420770332e-02, -1.53246341597736736e-02, 4.20291361748193881e-03};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_5[] = {
    3.45791791835113105e-01,  -4.94638823701766983e-01, 2.32700982261791756e-01,
    -1.31082086812848581e-01, 7.07661487158944280e-02,  -3.32311664679305063e-02,
    1.38345849225210826e-02,  -5.79296273169795876e-03, 1.65288291026933999e-03};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_6[] = {
    3.46177360874770079e-01, -4.97005359585988293e-01, 2.39238298635452873e-01, -1.42036658203261917e-01,
    8.39478592675435148e-02, -4.50956813087812561e-02, 2.07009764054380367e-02, -8.57882208536839622e-03,
    3.73645702728076694e-03, -1.08487244360550516e-03};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_7[] = {
    3.46468682743447387e-01, -4.99060441846808478e-01, 2.45979346429547135e-01, -1.55603351771571224e-01,
    1.02798920331395538e-01, -6.51428372035875447e-02, 3.79965193211083893e-02, -1.96129938771228453e-02,
    8.51796667695034135e-03, -3.49990324444903736e-03, 1.64828520828645621e-03, -4.90244168606017959e-04};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_8[] = {
    3.46519150735571824e-01, -4.99473711075286486e-01, 2.47560863981100110e-01, -1.59404941233487224e-01,
    1.09264632049333191e-01, -7.32609399355232949e-02, 4.57677006506466630e-02, -2.59573159176157316e-02,
    1.32358357921169446e-02, -5.94709367463631261e-03, 2.26595137107045343e-03, -8.19215573556561169e-04,
    3.41489111493683585e-04, -9.24085343018617470e-05};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_9[] = {
    3.46558679524847812e-01, -4.99834850211860637e-01, 2.49119199277336473e-01, -1.63639510952304751e-01,
    1.17422312190085157e-01, -8.51767864078933484e-02, 5.95417024913368273e-02, -3.88522855705760450e-02,
    2.31844720284554856e-02, -1.25568836236085758e-02, 6.19029095450276262e-03, -2.70350276174949377e-03,
    9.89234630104329250e-04, -3.61255417262498475e-04, 1.65073323779927277e-04, -4.58897637330004399e-05};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_10[] = {
    3.46565736631153143e-01, -4.99907483838147593e-01, 2.49474193193855942e-01, -1.64738596995519460e-01,
    1.19848226786064466e-01, -8.92458933743993515e-02, 6.49454929811426884e-02, -4.47241318333999258e-02,
    2.85320317877610155e-02, -1.66399873734038341e-02, 8.80197625127055079e-03, -4.22275855139565316e-03,
    1.85005998716256332e-03, -7.24135133333572690e-04, 2.40373469830557974e-04, -7.96763180834371540e-05,
    3.31537216045767031e-05, -8.58140495277231689e-06};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_11[] = {
    3.46569438544917008e-01, -4.99948172166116755e-01, 2.49687315852250735e-01, -1.65447983870321752e-01,
    1.21536716495854458e-01, -9.23129050508442600e-02, 6.93759616154990544e-02, -4.99598244971918015e-02,
    3.37034475479549775e-02, -2.09903206500092580e-02, 1.19580563471582569e-02, -6.19612863377783617e-03,
    2.92745217434708504e-03, -1.27338936535266868e-03, 4.95558628313796392e-04, -1.61953520652763686e-04,
    5.42155727055558800e-05, -2.37106642001809648e-05, 6.22564417452058528e-06};

// beta: 0
constexpr double esp_laplace_2d_potential_grad_12[] = {
    3.46572419186334690e-01, -4.99983734338924124e-01, 2.49890490129001885e-01, -1.66189269242562027e-01,
    1.23480378383596170e-01, -9.62211538819075368e-02, 7.56573041156004267e-02, -5.82648007363986351e-02,
    4.29282085819712375e-02, -2.97393061293908384e-02, 1.91454632870272819e-02, -1.13721975169510398e-02,
    6.20945182474741744e-03, -3.10964651516892985e-03, 1.42589296070909865e-03, -6.02154924850327325e-04,
    2.37188910790665021e-04, -8.43051474034488220e-05, 2.51246517177253442e-05, -7.86554630397245592e-06,
    3.35467646215108378e-06, -8.42728173519944100e-07};

template <class Real, int MaxVecLen>
residual_evaluator_func<Real> get_esp_laplace_2d_kernel(dmk_eval_type eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (eval_level == DMK_POTENTIAL) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 4;
            constexpr int NC0 = 4;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 5;
            constexpr int NC0 = 5;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 7;
            constexpr int NC0 = 7;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 9;
            constexpr int NC0 = 9;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 10;
            constexpr int NC0 = 10;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 12;
            constexpr int NC0 = 12;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 14;
            constexpr int NC0 = 14;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 16;
            constexpr int NC0 = 16;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 18;
            constexpr int NC0 = 18;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 19;
            constexpr int NC0 = 19;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 22;
            constexpr int NC0 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    } else if (eval_level == DMK_POTENTIAL_GRAD) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 4;
            constexpr int NC0 = 4;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 5;
            constexpr int NC0 = 5;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 7;
            constexpr int NC0 = 7;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 9;
            constexpr int NC0 = 9;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 10;
            constexpr int NC0 = 10;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 12;
            constexpr int NC0 = 12;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 14;
            constexpr int NC0 = 14;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 16;
            constexpr int NC0 = 16;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 18;
            constexpr int NC0 = 18;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 19;
            constexpr int NC0 = 19;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 22;
            constexpr int NC0 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_laplace_2d_potential_grad_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    }
    throw std::runtime_error("Unsupported eval_level/n_digits combination");
}

// Explicit instantiations
template residual_evaluator_func<float> get_esp_laplace_2d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_eval_type,
                                                                                                       int);
template residual_evaluator_func<double> get_esp_laplace_2d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_eval_type,
                                                                                                          int);

} // namespace dmk
