// Auto-generated by generate_aot_kernels. Do not edit.
// Unit: sqrt_laplace_3d
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>
#include <utility>
#include <vector>

namespace dmk {
constexpr int unroll_factor = 3;

// beta: 5.634
constexpr double sqrt_laplace_3d_potential_2[] = {1.66639685121228759e-01, -3.72953915884949028e-01,
                                                  3.29557157561368219e-01, -1.26453601528666415e-01};

// beta: 8.298
constexpr double sqrt_laplace_3d_potential_3[] = {7.91978589785346659e-02, -2.45556231979947831e-01,
                                                  3.10542894094654409e-01, -2.22210595880110412e-01,
                                                  1.10036966003753095e-01, -3.21968345732795563e-02};

// beta: 10.962
constexpr double sqrt_laplace_3d_potential_4[] = {
    3.63330830581356859e-02, -1.46897108702979756e-01, 2.58172198445237366e-01, -2.62483939309452519e-01,
    1.73229141234193473e-01, -8.23021132783420262e-02, 3.22518135742099893e-02, -8.31453182523136762e-03};

// beta: 13.626000000000001
constexpr double sqrt_laplace_3d_potential_5[] = {
    1.66949912633374414e-02, -8.31192981790163099e-02, 1.85061254218017307e-01, -2.46112910600663870e-01,
    2.20740470450016241e-01, -1.42387037970086672e-01, 6.84079736524102477e-02, -2.62021156736557785e-02,
    9.09443088932886286e-03, -2.17848788786685968e-03};

// beta: 16.29
constexpr double sqrt_laplace_3d_potential_6[] = {
    7.66135334798236003e-03, -4.53460064600191559e-02, 1.22365952894679164e-01, -2.00806900680655515e-01,
    2.26148637790386020e-01, -1.87250798075070168e-01, 1.17935909173898776e-01, -5.71933009584770294e-02,
    2.33877256550076192e-02, -9.40241516580353140e-03, 2.50030721515872613e-03};

// beta: 18.954
constexpr double sqrt_laplace_3d_potential_7[] = {
    3.51445342148692550e-03, -2.41014381042033189e-02, 7.64127033167854852e-02, -1.49397384737238348e-01,
    2.02775460932299673e-01, -2.04023245065494852e-01, 1.59015999180011691e-01, -9.92026665073098696e-02,
    5.01979960203051689e-02, -2.05177759693448737e-02, 7.39125485298571579e-03, -2.75745092701631771e-03,
    6.92124748007945205e-04};

// beta: 21.618000000000002
constexpr double sqrt_laplace_3d_potential_8[] = {
    1.61174988202417505e-03, -1.25691348601554235e-02, 4.57741335802777718e-02, -1.03820899225845559e-01,
    1.65091545579915067e-01, -1.96508862202331797e-01, 1.82562132481562472e-01, -1.36304342704379799e-01,
    8.37388361173495577e-02, -4.32045966025541017e-02, 1.87936207937851492e-02, -6.79699829910315398e-03,
    2.23671051124683289e-03, -7.95163500146314436e-04, 1.91270551293962389e-04};

// beta: 24.282
constexpr double sqrt_laplace_3d_potential_9[] = {
    7.39035238548680241e-04, -6.45859168795810852e-03, 2.65647508543220626e-02, -6.85773817502468436e-02,
    1.25051962795149518e-01, -1.71923502217809804e-01, 1.85788609906626573e-01, -1.62492820865026560e-01,
    1.17529845523670379e-01, -7.14785656307210387e-02, 3.71137792074310788e-02, -1.66995500536824583e-02,
    6.50031187391446764e-03, -2.14254985626222919e-03, 6.58848022803448763e-04, -2.27037761807801847e-04,
    5.28565437249281289e-05};

// beta: 26.946
constexpr double sqrt_laplace_3d_potential_10[] = {
    3.38831131733497099e-04, -3.27997311310871797e-03, 1.50363692967013275e-02, -4.35303625170772729e-02,
    8.95567105551411946e-02, -1.39729373330694601e-01, 1.72326147835233229e-01, -1.72918552984859697e-01,
    1.44243970824506990e-01, -1.01717326789266413e-01, 6.14446173599117879e-02, -3.21363795722774820e-02,
    1.47140447911997471e-02, -5.97011247357320286e-03, 2.13403962133055375e-03, -6.53487318786446689e-04,
    1.90651387895472024e-04, -6.44318883441207511e-05, 1.46171940583598262e-05};

// beta: 29.610000000000003
constexpr double sqrt_laplace_3d_potential_11[] = {
    1.55333911424860509e-04, -1.64987197832693901e-03, 8.34085475287905595e-03, -2.67623570882231550e-02,
    6.13251009959118812e-02, -1.07085208200108792e-01, 1.48499490336974321e-01, -1.68304846323130919e-01,
    1.59248455975876974e-01, -1.27893284668800983e-01, 8.83498267678457377e-02, -5.30497478285679933e-02,
    2.79177813322741726e-02, -1.30202312826225262e-02, 5.45558538824176056e-03, -2.02064852450546586e-03,
    6.32850797393553870e-04, -1.95798117146164769e-04, 7.47197332259662988e-05, -1.80059869400571431e-05};

// beta: 32.274
constexpr double sqrt_laplace_3d_potential_12[] = {
    7.12071070677504559e-05, -8.23351155758915800e-04, 4.55031052690462248e-03, -1.60272607034530959e-02,
    4.04822113467893513e-02, -7.82342839479691771e-02, 1.20541888710177097e-01, -1.52373450954484124e-01,
    1.61393659233772108e-01, -1.45597045258188285e-01, 1.13336109429034798e-01, -7.69524387193569748e-02,
    4.59924416706751285e-02, -2.43725255244627362e-02, 1.15167465681792619e-02, -4.89844488083774222e-03,
    1.89990326484568367e-03, -6.58700423507349868e-04, 1.93914528233811239e-04, -5.74185615178931822e-05,
    2.16076137692343146e-05, -5.07987035269845689e-06};

// beta: 8.298
constexpr double sqrt_laplace_3d_potential_grad_2[] = {7.89802449280127133e-02, -2.35548805368288455e-01,
                                                       3.12290771164578929e-01, -2.62384446480394495e-01,
                                                       1.08286760592471554e-01};

// beta: 10.962
constexpr double sqrt_laplace_3d_potential_grad_3[] = {
    3.63465256804728146e-02, -1.47800804637158889e-01, 2.57929434677331482e-01, -2.55231585449419152e-01,
    1.73877577113410425e-01, -9.68342397466479959e-02, 3.18190961551187076e-02};

// beta: 13.626000000000001
constexpr double sqrt_laplace_3d_potential_grad_4[] = {
    1.66248040829861526e-02, -8.31024263431551918e-02, 1.87319272394801117e-01, -2.46654868841845704e-01,
    2.09414076865696963e-01, -1.39671040645203914e-01, 8.65690428758947722e-02, -3.05543460542532543e-02};

// beta: 16.29
constexpr double sqrt_laplace_3d_potential_grad_5[] = {
    7.66618091725305983e-03, -4.53409654336876244e-02, 1.22123574420764533e-01, -2.00874295372418882e-01,
    2.28093026474940813e-01, -1.87007741371277458e-01, 1.12480865898401269e-01, -5.75177924237513655e-02,
    2.96312983665110719e-02, -9.25805793874532462e-03};

// beta: 18.954
constexpr double sqrt_laplace_3d_potential_grad_6[] = {
    3.51411915768513059e-03, -2.41018499635920619e-02, 7.64368509877199342e-02, -1.49389128215570516e-01,
    2.02493062783261568e-01, -2.04069559160185682e-01, 1.60223065432488515e-01, -9.90966724640134217e-02,
    4.78668243735029114e-02, -2.06238738074232125e-02, 9.46572804722171923e-03, -2.71883966701338530e-03};

// beta: 21.618000000000002
constexpr double sqrt_laplace_3d_potential_grad_7[] = {
    1.61177298443002017e-03, -1.25691020855052578e-02, 4.57718631850524763e-02, -1.03821818817198458e-01,
    1.65127948518738105e-01, -1.96501494031810109e-01, 1.82343356300377568e-01, -1.36329635572047692e-01,
    8.43647321968289399e-02, -4.31624010018129695e-02, 1.78746527212965932e-02, -6.83078153118692796e-03,
    2.90564999275443221e-03, -7.84761793558288773e-04};

// beta: 24.282
constexpr double sqrt_laplace_3d_potential_grad_8[] = {
    7.39033642042871610e-04, -6.45859424927859322e-03, 2.65649557005325464e-02, -6.85772859508420596e-02,
    1.25047652937917975e-01, -1.71924538341297561e-01, 1.85823140655049124e-01, -1.62487881255399091e-01,
    1.17394021879029434e-01, -7.14906516267174857e-02, 3.74038339303499473e-02, -1.66837159401374106e-02,
    6.15722191278053436e-03, -2.15311295991707161e-03, 8.70137678650751475e-04, -2.24219326420912465e-04};

// beta: 26.946
constexpr double sqrt_laplace_3d_potential_grad_9[] = {
    3.38831242132142457e-04, -3.27997291554629061e-03, 1.50363513740574793e-02, -4.35303720156173940e-02,
    8.95571893026800431e-02, -1.39729240174482183e-01, 1.72321225871979483e-01, -1.72919390879598678e-01,
    1.44269313069592620e-01, -1.01714531265053490e-01, 6.13713347175685112e-02, -3.21416697275711469e-02,
    1.48385076588159973e-02, -5.96441161908862170e-03, 2.01085485529744513e-03, -6.56746815795308412e-04,
    2.56391792932196268e-04, -6.36645634260495687e-05};

// beta: 29.610000000000003
constexpr double sqrt_laplace_3d_potential_grad_10[] = {
    1.55333919067746182e-04, -1.64987326987062091e-03, 8.34085351224265158e-03, -2.67622794341940487e-02,
    6.13251341340559294e-02, -1.07086577238952388e-01, 1.48499149658078117e-01, -1.68293878461220098e-01,
    1.59250210019094729e-01, -1.27940869196930457e-01, 8.83447546793649785e-02, -5.29284987367465223e-02,
    2.79263955855996865e-02, -1.32069350247974778e-02, 5.44705972349908158e-03, -1.84981446224861848e-03,
    6.37400657471720502e-04, -2.81274103918515100e-04, 7.37080957784227699e-05};

// beta: 32.274
constexpr double sqrt_laplace_3d_potential_grad_11[] = {
    7.12071065392950162e-05, -8.23351055056525038e-04, 4.55031063294344690e-03, -1.60272681020447241e-02,
    4.04822078407657063e-02, -7.82341238911463399e-02, 1.20541933653337791e-01, -1.52375038350935438e-01,
    1.61393366754883083e-01, -1.45588393087316637e-01, 1.13337202434098075e-01, -7.69807824083283826e-02,
    4.59899554795469220e-02, -2.43143351992718450e-02, 1.15202461534616631e-02, -4.97387178229021388e-03,
    1.89692675078037489e-03, -5.98762592574507229e-04, 1.95316012461516639e-04, -8.40735260247666794e-05,
    2.13271800906585903e-05};

// beta: 34.938
constexpr double sqrt_laplace_3d_potential_grad_12[] = {
    3.26407909116977195e-05, -4.08145985541612136e-04, 2.44792175171207544e-03, -9.39005809659832630e-03,
    2.59200788238149321e-02, -5.49311212173696634e-02, 9.31240300068331972e-02, -1.29941437790310949e-01,
    1.52407611196136827e-01, -1.52713682132779471e-01, 1.32423321989069809e-01, -1.00427435108102869e-01,
    6.72145604078629999e-02, -4.00128282102433439e-02, 2.13056327980733033e-02, -1.01876201105600139e-02,
    4.42471732486051685e-03, -1.77466182611472271e-03, 6.34675393337830423e-04, -1.88153609942894761e-04,
    5.86737114223496252e-05, -2.48559120845308420e-05, 6.13580588784667597e-06};

template <class Real, int MaxVecLen>
residual_evaluator_func<Real> get_sqrt_laplace_3d_kernel(dmk_eval_type eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (eval_level == DMK_POTENTIAL) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 4;
            constexpr int NC0 = 4;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 6;
            constexpr int NC0 = 6;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 8;
            constexpr int NC0 = 8;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 10;
            constexpr int NC0 = 10;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 11;
            constexpr int NC0 = 11;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 13;
            constexpr int NC0 = 13;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 15;
            constexpr int NC0 = 15;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 17;
            constexpr int NC0 = 17;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 19;
            constexpr int NC0 = 19;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 20;
            constexpr int NC0 = 20;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 22;
            constexpr int NC0 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    } else if (eval_level == DMK_POTENTIAL_GRAD) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 5;
            constexpr int NC0 = 5;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 7;
            constexpr int NC0 = 7;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 8;
            constexpr int NC0 = 8;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 10;
            constexpr int NC0 = 10;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 12;
            constexpr int NC0 = 12;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 14;
            constexpr int NC0 = 14;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 16;
            constexpr int NC0 = 16;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 18;
            constexpr int NC0 = 18;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 19;
            constexpr int NC0 = 19;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 21;
            constexpr int NC0 = 21;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 23;
            constexpr int NC0 = 23;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(sqrt_laplace_3d_potential_grad_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    }
    throw std::runtime_error("Unsupported eval_level/n_digits combination");
}

// Explicit instantiations
template residual_evaluator_func<float> get_sqrt_laplace_3d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_eval_type,
                                                                                                        int);
template residual_evaluator_func<double>
get_sqrt_laplace_3d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_eval_type, int);

} // namespace dmk
