// Auto-generated by generate_aot_kernels. Do not edit.
// Unit: esp_yukawa_2d
#include <algorithm>
#include <array>
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>
#include <utility>
#include <vector>

namespace dmk {
constexpr int unroll_factor = 3;

template <class Real, int MaxVecLen>
residual_evaluator_func<Real> get_esp_yukawa_2d_kernel(dmk_eval_type eval_level, int n_digits,
                                                       const std::vector<std::vector<Real>> &coeffs) {
    constexpr int UF = unroll_factor;
    const int n = static_cast<int>(coeffs.at(1).size());
    if (eval_level == DMK_POTENTIAL) {
        if (n == 3) {
            constexpr int NC0 = 3;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 4) {
            constexpr int NC0 = 4;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 5) {
            constexpr int NC0 = 5;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 6) {
            constexpr int NC0 = 6;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 7) {
            constexpr int NC0 = 7;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 8) {
            constexpr int NC0 = 8;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 9) {
            constexpr int NC0 = 9;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 10) {
            constexpr int NC0 = 10;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 11) {
            constexpr int NC0 = 11;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 12) {
            constexpr int NC0 = 12;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 13) {
            constexpr int NC0 = 13;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 14) {
            constexpr int NC0 = 14;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 15) {
            constexpr int NC0 = 15;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 16) {
            constexpr int NC0 = 16;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 17) {
            constexpr int NC0 = 17;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 18) {
            constexpr int NC0 = 18;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 19) {
            constexpr int NC0 = 19;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 20) {
            constexpr int NC0 = 20;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 21) {
            constexpr int NC0 = 21;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 22) {
            constexpr int NC0 = 22;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 23) {
            constexpr int NC0 = 23;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 24) {
            constexpr int NC0 = 24;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 25) {
            constexpr int NC0 = 25;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 26) {
            constexpr int NC0 = 26;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 27) {
            constexpr int NC0 = 27;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 28) {
            constexpr int NC0 = 28;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 29) {
            constexpr int NC0 = 29;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 30) {
            constexpr int NC0 = 30;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 31) {
            constexpr int NC0 = 31;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
    } else if (eval_level == DMK_POTENTIAL_GRAD) {
        if (n == 3) {
            constexpr int NC0 = 3;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 4) {
            constexpr int NC0 = 4;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 5) {
            constexpr int NC0 = 5;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 6) {
            constexpr int NC0 = 6;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 7) {
            constexpr int NC0 = 7;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 8) {
            constexpr int NC0 = 8;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 9) {
            constexpr int NC0 = 9;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 10) {
            constexpr int NC0 = 10;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 11) {
            constexpr int NC0 = 11;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 12) {
            constexpr int NC0 = 12;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 13) {
            constexpr int NC0 = 13;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 14) {
            constexpr int NC0 = 14;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 15) {
            constexpr int NC0 = 15;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 16) {
            constexpr int NC0 = 16;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 17) {
            constexpr int NC0 = 17;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 18) {
            constexpr int NC0 = 18;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 19) {
            constexpr int NC0 = 19;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 20) {
            constexpr int NC0 = 20;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 21) {
            constexpr int NC0 = 21;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 22) {
            constexpr int NC0 = 22;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 23) {
            constexpr int NC0 = 23;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 24) {
            constexpr int NC0 = 24;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 25) {
            constexpr int NC0 = 25;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 26) {
            constexpr int NC0 = 26;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 27) {
            constexpr int NC0 = 27;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 28) {
            constexpr int NC0 = 28;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 29) {
            constexpr int NC0 = 29;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 30) {
            constexpr int NC0 = 30;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
        if (n == 31) {
            constexpr int NC0 = 31;
            const int n_log = static_cast<int>(coeffs[0].size());
            std::vector<Real> cf;
            cf.reserve(n_log + NC0);
            cf.insert(cf.end(), coeffs[0].begin(), coeffs[0].end());
            cf.insert(cf.end(), coeffs[1].begin(), coeffs[1].end());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                yukawa_2d_poly_all_pairs<Real, MaxVecLen, -1, -1, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, n_digits, rsc, cen, d2max, thresh2, n_log, NC0, cf.data(), n_src, r_src, charge,
                    normals, n_trg, r_trg, pot, UF);
            };
        }
    }
    throw std::runtime_error("Unsupported eval_level, or n_coeffs outside the AOT range");
}

// Explicit instantiations
template residual_evaluator_func<float>
get_esp_yukawa_2d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_eval_type, int,
                                                              const std::vector<std::vector<float>> &);
template residual_evaluator_func<double>
get_esp_yukawa_2d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_eval_type, int,
                                                                const std::vector<std::vector<double>> &);

} // namespace dmk
