// Auto-generated by generate_aot_kernels. Do not edit.
// Unit: laplace_dipole_3d
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>
#include <utility>
#include <vector>

namespace dmk {
constexpr int unroll_factor = 3;

// beta: 8.298
constexpr double laplace_dipole_3d_potential_2[] = {1.35373393795720692e-01, -4.36907496688934471e-01,
                                                    4.49104115534396831e-01, -6.54190101699606286e-02,
                                                    -8.50658566475083061e-02};

// beta: 10.962
constexpr double laplace_dipole_3d_potential_3[] = {8.60612156248130727e-02,  -3.40111927203895936e-01,
                                                    4.97659587015112592e-01,  -2.50082439360021058e-01,
                                                    -8.37086507244033384e-02, 9.08624864724610626e-02};

// beta: 13.626000000000001
constexpr double laplace_dipole_3d_potential_4[] = {
    5.58390435893020218e-02,  -2.64717167590847735e-01, 4.87559575065030892e-01,
    -3.83241492306865494e-01, 8.96132752589977148e-03,  1.79344646567271587e-01,
    -7.28417849593808592e-02, -3.14007565336095265e-02, 2.05017147121834692e-02};

// beta: 16.29
constexpr double laplace_dipole_3d_potential_5[] = {
    3.65651153834012990e-02, -2.02336522120227985e-01, 4.50703044165623401e-01,  -4.71988793396330319e-01,
    1.30713175727858899e-01, 2.01028804034472791e-01,  -1.73501647366733819e-01, -2.40526631146708372e-02,
    6.67882926557134132e-02, -2.65352836539563090e-03, -1.12698283550172283e-02};

// beta: 18.954
constexpr double laplace_dipole_3d_potential_6[] = {
    2.41435365819562368e-02, -1.52718808764497921e-01, 3.98897944342020083e-01,  -5.19356388662591928e-01,
    2.61731244800182006e-01, 1.55627597162875442e-01,  -2.66978590303516672e-01, 5.19699102108855393e-02,
    9.97763197131621704e-02, -4.56454000595140560e-02, -1.90998195412067882e-02, 1.01237641756432902e-02,
    1.52931819491995431e-03};

// beta: 21.618000000000002
constexpr double laplace_dipole_3d_potential_7[] = {
    1.60439680211329795e-02,  -1.14126099610511914e-01, 3.41984271196447198e-01,  -5.32521756854699824e-01,
    3.82908730215659632e-01,  6.19079603329049238e-02,  -3.28690650132687112e-01, 1.72357352569426858e-01,
    9.15769080873981428e-02,  -1.23584312439697891e-01, 3.41197217941373396e-03,  4.46349951564157174e-02,
    -9.27357818320668700e-03, -9.75130738557921685e-03, 2.03839781997119636e-03,  1.08317173001665928e-03};

// beta: 24.282
constexpr double laplace_dipole_3d_potential_8[] = {
    1.07159462374928523e-02,  -8.46341793364562833e-02, 2.86172289845876782e-01,  -5.18873461702700878e-01,
    4.81157708128312989e-01,  -6.26959661442080818e-02, -3.41881484578489769e-01, 3.02447220896404911e-01,
    2.83287777506400426e-02,  -1.85181087225704200e-01, 6.73483269472894552e-02,  5.81198065641782002e-02,
    -4.33665484079018421e-02, -9.86037397693287181e-03, 1.34367184014683710e-02,  6.78038463523805333e-04,
    -1.91174021845368926e-03};

// beta: 26.946
constexpr double laplace_dipole_3d_potential_9[] = {
    7.18708246440367265e-03,  -6.23865649137638756e-02, 2.34945437005272401e-01,  -4.86161760244670338e-01,
    5.50173433125147771e-01,  -2.02352457277721304e-01, -3.00912710492949653e-01, 4.23092619570351436e-01,
    -8.84613031406586287e-02, -2.14495407348589684e-01, 1.62267009118026828e-01,  3.59486417552733750e-02,
    -8.86671064485698157e-02, 1.50553796593915507e-02,  2.86417091603183814e-02,  -1.18732171211611646e-02,
    -5.75137033229802461e-03, 3.67017900763767562e-03,  5.77819645270764371e-04,  -4.97413300023614720e-04};

// beta: 29.610000000000003
constexpr double laplace_dipole_3d_potential_10[] = {
    4.83699364701164342e-03,  -4.57629949453203164e-02, 1.89944146189103547e-01,  -4.41694815805404428e-01,
    5.88938361753583606e-01,  -3.40295594190500927e-01, -2.09477327720605233e-01, 5.10382635298455400e-01,
    -2.47328995077170849e-01, -1.90335030062067756e-01, 2.70747291815721935e-01,  -3.19599348895081709e-02,
    -1.26400907973926058e-01, 6.56380950546598396e-02,  3.23455685814820898e-02,  -3.54431405368228966e-02,
    -3.15749917183956626e-03, 1.16554507911594430e-02,  -6.25242294921542078e-04, -2.44259444406770901e-03,
    1.77610289495549849e-04,  2.57923748564379933e-04};

// beta: 32.274
constexpr double laplace_dipole_3d_potential_11[] = {
    3.26488932935758936e-03,  -3.34334184589342026e-02, 1.51628119013288543e-01,  -3.91438303230557672e-01,
    6.00144893739365637e-01,  -4.63260698656872971e-01, -7.91095963485347747e-02, 5.46371422708288978e-01,
    -4.25334996766092766e-01, -9.77511664059468321e-02, 3.64031957093882585e-01,  -1.51956009896253158e-01,
    -1.30781688719692979e-01, 1.40134444080656562e-01,  5.60786571449403779e-03,  -6.44986132385584748e-02,
    1.87924679144229438e-02,  1.91671466716092885e-02,  -1.13661256210334030e-02, -3.74395560480559296e-03,
    3.84651785292284892e-03,  4.28341104036052773e-04,  -8.07875592590791974e-04, -1.91890722053818430e-05,
    8.35723911323348051e-05};

// beta: 34.938
constexpr double laplace_dipole_3d_potential_12[] = {
    2.20928059493365235e-03,  -2.43426875242211231e-02, 1.19761893706071723e-01,  -3.39856659040368825e-01,
    5.88505140797872417e-01,  -5.62618110858054132e-01, 7.48570909907567972e-02,  5.22999143696575630e-01,
    -5.95015655106605257e-01, 6.28415423705892401e-02,  4.10829665279586365e-01,  -3.12678103311007982e-01,
    -7.88556227096840062e-02, 2.21754901069865118e-01,  -6.05635485305918708e-02, -8.38912139235251930e-02,
    5.89552927275863239e-02,  1.58589038944522143e-02,  -2.78508907904069791e-02, 1.30941825171451503e-03,
    8.91950669951599787e-03,  -1.86784537729052513e-03, -2.04171779144781936e-03, 5.57931216423200984e-04,
    3.14659759362786421e-04,  -6.72204654220478630e-05, -2.50956269826985266e-05};

// beta: 10.962
constexpr double laplace_dipole_3d_potential_grad_2[] = {8.62385196222487382e-02, -3.69606890598850102e-01,
                                                         4.96528359242903339e-01, -1.35056019181326203e-01,
                                                         -8.26655143090101602e-02};

// beta: 13.626000000000001
constexpr double laplace_dipole_3d_potential_grad_3[] = {
    5.58390435893020218e-02,  -2.68224601604254487e-01, 4.89913880123119205e-01, -3.55473001377395126e-01,
    -9.41724969141645094e-03, 1.24158739588970515e-01,  -3.66153264211257837e-02};

// beta: 16.29
constexpr double laplace_dipole_3d_potential_grad_4[] = {
    3.65651153834012574e-02,  -2.02219699079765197e-01, 4.51113257897009567e-01,
    -4.73415552498067493e-01, 1.25319537002709064e-01,  2.05866251141961998e-01,
    -1.54263382045602748e-01, -3.02262697822126523e-02, 4.13057433149017009e-02};

// beta: 18.954
constexpr double laplace_dipole_3d_potential_grad_5[] = {
    2.41428264185806554e-02, -1.52727869680320011e-01, 3.98949974709263577e-01,  -5.19177765526997237e-01,
    2.61117386337001989e-01, 1.54637461300230455e-01,  -2.64338880048808067e-01, 5.42159245410239812e-02,
    9.46559170453594445e-02, -4.78782113257822800e-02, -1.45280446299070731e-02, 1.09318845545621941e-02};

// beta: 21.618000000000002
constexpr double laplace_dipole_3d_potential_grad_6[] = {
    1.60442397518085061e-02,  -1.14125963916594200e-01, 3.41958267358202006e-01,  -5.32534965218171563e-01,
    3.83317532269755568e-01,  6.21182126658174905e-02,  -3.31110384703709348e-01, 1.71100900312455118e-01,
    9.84161626308610038e-02,  -1.20006039185096711e-01, -6.53102794862081212e-03, 3.94007856926334443e-02,
    -2.09499861869103486e-03, -5.95305557781742548e-03};

// beta: 24.282
constexpr double laplace_dipole_3d_potential_grad_7[] = {
    1.07160079128625838e-02,  -8.46341158092657198e-02, 2.86164499021600849e-01,  -5.18875766767919577e-01,
    4.81319657371681087e-01,  -6.26716138228798347e-02, -3.43166628407990892e-01, 3.02333276254381500e-01,
    3.33443644897920902e-02,  -1.84906521509741906e-01, 5.67068599479376018e-02,  5.77646395912575078e-02,
    -3.08482687716683940e-02, -9.62597357990953133e-03, 5.76355781306377938e-03,  6.16069860444641874e-04};

// beta: 26.946
constexpr double laplace_dipole_3d_potential_grad_8[] = {
    7.18708696662491778e-03,  -6.23865689551251629e-02, 2.34944710690734387e-01,  -4.86161114286023543e-01,
    5.50192734853164001e-01,  -2.02369500338105940e-01, -3.01110304866148037e-01, 4.23266087435998251e-01,
    -8.74475787629959700e-02, -2.15381152490050520e-01, 1.59344583655217781e-01,  3.84920455777423495e-02,
    -8.37167992995778570e-02, 1.07615211220452502e-02,  2.37535306040852282e-02,  -7.64544525195382310e-03,
    -3.14796804429392455e-03, 1.42413054340977422e-03};

// beta: 29.610000000000003
constexpr double laplace_dipole_3d_potential_grad_9[] = {
    4.83699326096378480e-03,  -4.57629954580399262e-02, 1.89944221480222636e-01,  -4.41694714069628958e-01,
    5.88935927419048988e-01,  -3.40298929884357115e-01, -2.09446691925963741e-01, 5.10425103847264250e-01,
    -2.47525302437725081e-01, -1.90609828373504236e-01, 2.71471275139919088e-01,  -3.09379896488533174e-02,
    -1.28029034250649959e-01, 6.33232710359899059e-02,  3.46146441220189921e-02,  -3.21966583676554161e-02,
    -5.07059312783855829e-03, 8.90306557998376234e-03,  2.68560059999608245e-04,  -1.15032511431834169e-03};

// beta: 32.274
constexpr double laplace_dipole_3d_potential_grad_10[] = {
    3.26488932935758936e-03,  -3.34334185506430376e-02, 1.51628119493200181e-01,  -3.91438294942497100e-01,
    6.00144851831136861e-01,  -4.63260918760944662e-01, -7.91085138437753604e-02, 5.46374110005457214e-01,
    -4.25347914237247993e-01, -9.77693410806410035e-02, 3.64117657338724032e-01,  -1.51881085092464729e-01,
    -1.31129249398179382e-01, 1.39936439149828284e-01,  6.51349223744272701e-03,  -6.41561071253722026e-02,
    1.72450849082454623e-02,  1.87813212539231812e-02,  -9.64179204742389613e-03, -3.47131547998901814e-03,
    2.63966265771625437e-03,  3.18610628889500901e-04,  -3.26288287241088381e-04};

// beta: 34.938
constexpr double laplace_dipole_3d_potential_grad_11[] = {
    2.20928059493365235e-03,  -2.43426874167138145e-02, 1.19761893744165224e-01,  -3.39856670097353264e-01,
    5.88505136847381705e-01,  -5.62617773502591567e-01, 7.48572123686999658e-02,  5.22994363348513347e-01,
    -5.95017385431159895e-01, 6.28795154646747956e-02,  4.10843482479753275e-01,  -3.12864733302772646e-01,
    -7.89238443713683874e-02, 2.22354547276362474e-01,  -6.03434581580932633e-02, -8.51869204020025417e-02,
    5.84780012910704819e-02,  1.77559686951297667e-02,  -2.71498128653384109e-02, -5.46958996643641697e-04,
    8.23146016803313549e-03,  -7.05186804239541398e-04, -1.60965058569251533e-03, 1.36535741088278140e-04,
    1.57683919047350445e-04};

// beta: 37.602000000000004
constexpr double laplace_dipole_3d_potential_grad_12[] = {
    1.49823059313269804e-03,  -1.76723677453100407e-02, 9.37416850035556748e-02,  -2.90036032576421687e-01,
    5.59493501073330068e-01,  -6.34136265052617221e-01, 2.36525018454831704e-01,  4.41573031874518573e-01,
    -7.30140015822103861e-01, 2.76879521960966934e-01,  3.83892966507353994e-01,  -4.87141707988068162e-01,
    4.70954151879119862e-02,  2.81242356731793708e-01,  -1.71882770391268508e-01, -7.21116911333790495e-02,
    1.15715198336007838e-01,  -9.32251397240195685e-03, -4.64092892516939151e-02, 1.65508950546909735e-02,
    1.24073890916912687e-02,  -7.42335693525890492e-03, -2.11885570946907615e-03, 1.79751538166786655e-03,
    1.82721599378981371e-04,  -1.99385600891264998e-04, -1.19467253448366012e-06};

template <class Real, int MaxVecLen>
residual_evaluator_func<Real> get_laplace_dipole_3d_kernel(dmk_eval_type eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (eval_level == DMK_POTENTIAL) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 5;
            constexpr int NC0 = 5;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 6;
            constexpr int NC0 = 6;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 9;
            constexpr int NC0 = 9;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 11;
            constexpr int NC0 = 11;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 13;
            constexpr int NC0 = 13;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 16;
            constexpr int NC0 = 16;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 17;
            constexpr int NC0 = 17;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 20;
            constexpr int NC0 = 20;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 22;
            constexpr int NC0 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 25;
            constexpr int NC0 = 25;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 27;
            constexpr int NC0 = 27;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    } else if (eval_level == DMK_POTENTIAL_GRAD) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 5;
            constexpr int NC0 = 5;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 7;
            constexpr int NC0 = 7;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 9;
            constexpr int NC0 = 9;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 12;
            constexpr int NC0 = 12;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 14;
            constexpr int NC0 = 14;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 16;
            constexpr int NC0 = 16;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 18;
            constexpr int NC0 = 18;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 20;
            constexpr int NC0 = 20;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 23;
            constexpr int NC0 = 23;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 25;
            constexpr int NC0 = 25;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 27;
            constexpr int NC0 = 27;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(laplace_dipole_3d_potential_grad_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                laplace_dipole_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    }
    throw std::runtime_error("Unsupported eval_level/n_digits combination");
}

// Explicit instantiations
template residual_evaluator_func<float> get_laplace_dipole_3d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_eval_type,
                                                                                                          int);
template residual_evaluator_func<double>
get_laplace_dipole_3d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_eval_type, int);

} // namespace dmk
