// Auto-generated by generate_aot_kernels. Do not edit.
// Unit: stresslet_3d
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>
#include <utility>
#include <vector>

namespace dmk {
constexpr int unroll_factor = 3;

// beta: 7.330382858376184
constexpr double stresslet_3d_velocity_2[] = {
    -4.19178842076952662e-01, -6.08037680909284894e-01, 5.80363383580482339e-01, 9.44902378821794509e-01,
    -3.29750195411952440e-01, -5.31756097781575621e-01, 8.88591765689311780e-02, 1.15169586425361681e-01,
    -4.47344763353390240e-01, 2.18978157963409720e-01,  2.89113662952478534e-01, 3.90790954415637798e-02,
    -1.57127878700818902e-01, -3.75748637845388575e-02, 3.62241272219490998e-02};

// beta: 10.471975511965976
constexpr double stresslet_3d_velocity_3[] = {
    -4.91085066317953012e-01, -2.63833945032233452e-01, 1.43344621801229111e+00,  5.13328671640693623e-01,
    -1.74461134163701237e+00, -3.33205091867165459e-01, 1.12166096958292361e+00,  7.93180215257236060e-02,
    -3.95916409421479709e-01, -5.74509500578884464e-03, 6.63781670851546629e-02,  -3.87611908034877217e-01,
    4.02925646456617936e-01,  3.63607665530838065e-01,  -2.28118473401997202e-01, -4.00756468509649411e-01,
    8.90854625415453127e-02,  2.27350603487043140e-01,  -1.75169851571530533e-02, -5.62519753439864809e-02};

// beta: 12.566370614359172
constexpr double stresslet_3d_velocity_4[] = {
    -4.94652564695905406e-01, 3.20886713961663975e-02,  1.70994978597343139e+00, -3.31491031777576550e-01,
    -2.40084934569405384e+00, 7.18527949960816259e-01,  1.76753708436099188e+00, -6.52315623279344892e-01,
    -7.55700991488769125e-01, 2.83792175613758635e-01,  1.98301369831513946e-01, -5.28477300602359576e-02,
    -2.68289480455389147e-02, -3.44476612152515904e-01, 5.05362067133610871e-01, 3.06381434824991639e-01,
    -5.05169905748385162e-01, -4.18910656951901161e-01, 4.18282683878486383e-01, 3.10193397969663776e-01,
    -2.44313608663528137e-01, -1.27651746780275410e-01, 9.16893917280850596e-02, 2.36862452967999196e-02,
    -1.66328363078935386e-02};

// beta: 14.660765716752367
constexpr double stresslet_3d_velocity_5[] = {
    -4.75726426158035121e-01, 3.17468547344523566e-01, 1.73032099519823057e+00,  -1.35180168682556223e+00,
    -2.47824238303881250e+00, 2.28307045674053644e+00, 1.77688688548169438e+00,  -2.00762094071336694e+00,
    -6.80645307330958294e-01, 1.02415813752500329e+00, 1.37336636423054353e-01,  -3.11727550369678197e-01,
    -9.26040394843478075e-03, 4.60142751320577886e-02, -1.10934960040861338e-03, -3.01673511657453763e-01,
    5.81552131627964153e-01,  1.80184268102269590e-01, -7.63057803492756426e-01, -2.53965258256377335e-01,
    7.99558868261849187e-01,  1.80855139740863646e-01, -5.72219723815157844e-01, -6.44405960559882030e-02,
    2.75285348732874469e-01,  8.51790177862657254e-03, -8.40436711862239672e-02, 3.71923898502578352e-04,
    1.27749257768888357e-02};

// beta: 17.80235837034216
constexpr double stresslet_3d_velocity_6[] = {
    -4.22399917184285212e-01, 6.63949630543667624e-01,  1.36286332976560254e+00,  -2.73840684829410463e+00,
    -1.35275216770362317e+00, 4.60734844982403580e+00,  -8.96041123462983369e-02, -4.15868518269884380e+00,
    1.16600815593644636e+00,  2.27445574470521805e+00,  -1.03162187822957829e+00, -8.23400957286753221e-01,
    4.84271905261834001e-01,  2.06584264409916840e-01,  -1.34925049793606977e-01, -3.51197991744877508e-02,
    1.81250199343182296e-02,  3.23995795408940765e-03,  -2.41596787940864144e-01, 6.43716252650913257e-01,
    -8.88884447536850697e-02, -1.00496344337819599e+00, 3.02843501836697948e-01,  1.20320601495180757e+00,
    -5.20980352890353826e-01, -9.51776933438070571e-01, 5.30148710667554313e-01,  5.00641825367875493e-01,
    -3.44475367732028415e-01, -1.76194561622649487e-01, 1.47936243633985304e-01,  4.00047177462431666e-02,
    -4.05200677276419188e-02, -4.64573531331626682e-03, 5.52072820627928004e-03};

// beta: 19.896753472735355
constexpr double stresslet_3d_velocity_7[] = {
    -3.78954689301535086e-01, 8.24338589531620869e-01,  9.46557494397167409e-01,  -3.35296872109087429e+00,
    4.14097965919434999e-02,  5.50136599678207538e+00,  -2.48482449781325965e+00, -4.70534929728549312e+00,
    3.63134990064831253e+00,  2.26171327539375744e+00,  -2.70310118624998053e+00, -5.75692372466708679e-01,
    1.28968574124848812e+00,  1.60293029170643468e-02,  -4.24792064349734766e-01, 4.49856331323180147e-02,
    9.32015702001319224e-02,  -1.68149198880346816e-02, -1.05381422443668066e-02, 2.38644057862675250e-03,
    -2.05709286043797929e-01, 6.53734275358172523e-01,  -2.86127696171484258e-01, -1.03208095034339631e+00,
    7.87867497463798361e-01,  1.20631721793876734e+00,  -1.22229128399619436e+00, -8.76249106096256392e-01,
    1.19287741339284814e+00,  3.68246513155864985e-01,  -7.79351817349422937e-01, -6.24534639677213066e-02,
    3.56475844566667976e-01,  -1.72866441817045302e-02, -1.16650059908158438e-01, 1.19180185233117835e-02,
    2.59077509643449271e-02,  -2.14791586043308917e-03, -3.00041783750080874e-03};

// beta: 23.03834612632515
constexpr double stresslet_3d_velocity_8[] = {
    -3.11817968419713709e-01, 9.60677269085545626e-01,  2.24858499575687432e-01,  -3.66459166171365203e+00,
    2.52930918150038275e+00,  5.21681525413985803e+00,  -6.77060705417731157e+00, -2.93737708110089857e+00,
    7.96143120964660955e+00,  -4.97981212737636236e-01, -5.48572242070985894e+00, 1.84864367450706424e+00,
    2.48174656425663764e+00,  -1.40906301760737329e+00, -7.73910811194231996e-01, 6.51412944098829549e-01,
    1.65741839608624930e-01,  -2.07936888678166454e-01, -2.25000890788596003e-02, 4.42090559796847263e-02,
    1.47064859749760886e-03,  -4.80873673410419592e-03, -1.59100262336534626e-01, 6.32043724854668754e-01,
    -5.61294789526922910e-01, -8.72318310480426518e-01, 1.49734193452310937e+00,  7.09685591879294808e-01,
    -2.26862953191274253e+00, -1.81673339143300998e-03, 2.16585172747563393e+00,  -6.16850502164480785e-01,
    -1.37306705410847973e+00, 7.00801033961516717e-01,  5.95823984073511670e-01,  -4.46931482755483167e-01,
    -1.78740963359977911e-01, 1.94737279950644215e-01,  3.58541559884833425e-02,  -6.07725157926479534e-02,
    -4.23510784595171504e-03, 1.28112313801403230e-02,  1.95771596909031121e-04,  -1.38945296234593472e-03};

// beta: 25.132741228718345
constexpr double stresslet_3d_velocity_9[] = {
    -2.69206248562092854e-01, 9.91975201477445334e-01,  -2.47527663529142489e-01, -3.48304729199207186e+00,
    4.11045017644510224e+00,  3.90228829634805541e+00,  -9.28159114013751463e+00, 1.40285664358437340e-01,
    1.00585333540418418e+01,  -4.43306367021740133e+00, -6.25066772768635825e+00, 5.07471339507466723e+00,
    2.26254090081558257e+00,  -3.26163151787991712e+00, -3.23001899655737390e-01, 1.44359064432443329e+00,
    -1.37405572342816168e-01, -4.73281815360943992e-01, 1.09912676172327375e-01,  1.16308566478447839e-01,
    -3.97147877315543810e-02, -1.99488235067876614e-02, 8.57975263120846175e-03,  1.81128440915534266e-03,
    -9.01886973362098459e-04, -1.32862383291737801e-01, 5.99864648916903720e-01,  -7.13099955964804022e-01,
    -6.58112713871953137e-01, 1.86373506434064540e+00,  8.38047712363614306e-02,  -2.73012222913875036e+00,
    1.06092168894395833e+00,  2.44800388676345859e+00,  -1.79095409373708248e+00, -1.35879414396530662e+00,
    1.60063069511502842e+00,  4.16398148970831217e-01,  -9.48223338120393944e-01, -7.90898811876387248e-03,
    4.06502837297393504e-01,  -5.94128236154697065e-02, -1.31688808755656445e-01, 3.14112127739896996e-02,
    3.23255256325086990e-02,  -8.35413881379685162e-03, -5.58633400506599632e-03, 1.00632769998309146e-03,
    5.15098968644662927e-04};

// beta: 28.274333882308134
constexpr double stresslet_3d_velocity_10[] = {
    -2.11678730168907786e-01, 9.71795507714212636e-01,  -8.60458806169051238e-01, -2.76019378159103912e+00,
    5.92226278478731771e+00,  6.39561300947636302e-01,  -1.13321723368626177e+01, 6.82127074344689177e+00,
    1.00034053963851459e+01,  -1.23336066587850688e+01, -3.42170764012660467e+00, 1.10468795306750156e+01,
    -1.56221770798992265e+00, -6.27415056073728294e+00, 2.62984568375489625e+00,  2.43567845991149534e+00,
    -1.73150652862773513e+00, -6.43373760666963057e-01, 7.61801245685391204e-01,  9.97463475543416550e-02,
    -2.49596017696076061e-01, -8.62650763890565348e-04, 6.16707015340394044e-02,  -3.27551576047314854e-03,
    -1.06016244518119130e-02, 5.31034066219678502e-04,  9.53575956725815125e-04,  -1.00250316449018245e-01,
    5.35610566102509233e-01,  -8.78556723932091055e-01, -2.38753582158550887e-01, 2.15315294273444380e+00,
    -1.11451751297120882e+00, -2.77756732051620236e+00, 3.03564277804704874e+00,  1.81519908899413673e+00,
    -3.87218351356029888e+00, -1.22592081478356082e-01, 3.06762199654645729e+00,  -8.76710022472523165e-01,
    -1.64135251295926787e+00, 9.03535454223332479e-01,  6.07823226361887015e-01,  -5.31434305817833241e-01,
    -1.48557222992412030e-01, 2.18367250400962526e-01,  1.72797484974820947e-02,  -6.46610263571143207e-02,
    2.68186254013996544e-03,  1.27963863344786807e-02,  -1.50834434656959334e-03, -1.27932701265125095e-03,
    2.12509553469837989e-04};

// beta: 30.36872898470133
constexpr double stresslet_3d_velocity_11[] = {
    -1.78351138747854299e-01, 9.26543511073967263e-01,  -1.18040197625607846e+00, -2.08077648054096498e+00,
    6.61293894367558810e+00,  -2.01050142993505299e+00, -1.11518139728928602e+01, 1.17513808845566228e+01,
    7.14764312210650754e+00,  -1.74780494770034593e+01, 1.88588058007170645e+00,  1.40630458886740186e+01,
    -7.03656336463413723e+00, -6.89329118139324226e+00, 6.42401688698595041e+00,  1.88204508160273321e+00,
    -3.64556920221993064e+00, 8.62216220942639902e-03,  1.49627847764955457e+00,  -2.84613500730220514e-01,
    -4.70600392633574338e-01, 1.57115148272001265e-01,  1.15706029290487747e-01,  -5.06596089942367503e-02,
    -2.18793875900817197e-02, 1.01218931629362824e-02,  2.92531838402885873e-03,  -9.82891574358403779e-04,
    -2.09923808319195475e-04, -8.25446250761062983e-02, 4.87198975780796351e-01,  -9.45914650505286336e-01,
    6.81733808394492935e-02,  2.15318295628278999e+00,  -1.95185086666824148e+00, -2.31411824652276543e+00,
    4.30753974447391919e+00,  5.72017309624473835e-01,  -5.01082944618726511e+00, 1.64273712668650518e+00,
    3.59425710897589079e+00,  -2.51500289407781663e+00, -1.59976041669421121e+00, 1.98511689612367870e+00,
    3.43991877260653334e-01,  -1.06608528894710664e+00, 7.89856005419907192e-02,  4.24566260796283346e-01,
    -1.06519933214526297e-01, -1.29399444360196542e-01, 5.22188756781552382e-02,  2.98041285181855076e-02,
    -1.63458927500373698e-02, -4.75657683782852638e-03, 3.26150510995041254e-03,  3.97048087614278948e-04,
    -3.20513354984615839e-04};

// beta: 33.510321638291124
constexpr double stresslet_3d_velocity_12[] = {
    -1.36068382632040019e-01, 8.30206663514010845e-01,  -1.51492871813114438e+00, -9.38161731679668320e-01,
    6.81371900885790716e+00,  -5.98886386329479059e+00, -8.47250818086918578e+00, 1.80974147359075346e+01,
    -1.27353252176920551e+00, -2.20361156131437212e+01, 1.43959718912688448e+01,  1.35219326406985303e+01,
    -1.84739354442709001e+01, -2.44492107609423615e+00, 1.34202436784636507e+01,  -3.07394173611456978e+00,
    -6.52803236221760130e+00, 3.39530629009284146e+00,  2.19573400711340527e+00,  -1.97213541430062644e+00,
    -4.70416030102116911e-01, 8.13087237720465095e-01,  3.22988004424934194e-02,  -2.55438052531020809e-01,
    1.69538475357311168e-02,  6.07577487914693348e-02,  -6.26726435164908814e-03, -9.97434907897546373e-03,
    7.67670626394760416e-04,  8.46519477241623069e-04,  -6.11507944910260545e-02, 4.12803937136142662e-01,
    -9.88113762453371125e-01, 5.14347344280230212e-01,  1.88547916169623697e+00,  -3.05042335312181967e+00,
    -9.47579259804225860e-01, 5.63432412407424899e+00,  -2.33830851447116705e+00, -5.50271545724852196e+00,
    5.34387667869330407e+00,  2.70293690603821268e+00,  -5.63078788803793984e+00, 1.19439080008556173e-01,
    3.78034491933946892e+00,  -1.27239595926929594e+00, -1.75151091431009642e+00, 1.11608523419285377e+00,
    5.57849478448433023e-01,  -6.07791533305840348e-01, -1.04925278872826697e-01, 2.43734056081953088e-01,
    -5.58136197206675019e-04, -7.54926424650251143e-02, 7.36565035941283506e-03,  1.78115945261800579e-02,
    -2.24202640239685785e-03, -2.90945558305993413e-03, 2.60686491503111422e-04,  2.46124643278450327e-04};

template <class Real, int MaxVecLen>
residual_evaluator_func<Real> get_stresslet_3d_kernel(dmk_eval_type eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (eval_level == DMK_VELOCITY) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 15;
            constexpr int NC0 = 8;
            constexpr int NC1 = 7;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 20;
            constexpr int NC0 = 11;
            constexpr int NC1 = 9;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 25;
            constexpr int NC0 = 13;
            constexpr int NC1 = 12;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 29;
            constexpr int NC0 = 15;
            constexpr int NC1 = 14;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 35;
            constexpr int NC0 = 18;
            constexpr int NC1 = 17;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 39;
            constexpr int NC0 = 20;
            constexpr int NC1 = 19;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 44;
            constexpr int NC0 = 22;
            constexpr int NC1 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 49;
            constexpr int NC0 = 25;
            constexpr int NC1 = 24;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 53;
            constexpr int NC0 = 27;
            constexpr int NC1 = 26;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 57;
            constexpr int NC0 = 29;
            constexpr int NC1 = 28;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 60;
            constexpr int NC0 = 30;
            constexpr int NC1 = 30;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(stresslet_3d_velocity_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                stresslet_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, NC1, DMK_VELOCITY>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, NC1, coeffs.data(), n_src, r_src, charge, normals,
                    n_trg, r_trg, pot, UF);
            };
        }
    }
    throw std::runtime_error("Unsupported eval_level/n_digits combination");
}

// Explicit instantiations
template residual_evaluator_func<float> get_stresslet_3d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_eval_type,
                                                                                                     int);
template residual_evaluator_func<double> get_stresslet_3d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_eval_type,
                                                                                                        int);

} // namespace dmk
