// Auto-generated by generate_aot_kernels. Do not edit.
// Unit: esp_sqrt_laplace_3d
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>
#include <utility>
#include <vector>

namespace dmk {
constexpr int unroll_factor = 3;

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_2[] = {8.96381467338864951e-02, -2.57182183283078958e-01,
                                                      3.17288970308536367e-01, -2.41196782850746916e-01,
                                                      9.27549072282227577e-02};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_3[] = {5.09815427800193316e-02, -1.84031646905249174e-01,
                                                      2.75837970519588749e-01, -2.51598622358623292e-01,
                                                      1.72591084616892460e-01, -6.42423032140182620e-02};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_4[] = {
    1.58081037559418582e-02, -8.00181112755787155e-02, 1.83069081452299498e-01, -2.44402088446964344e-01,
    2.09928540281145243e-01, -1.42859005708558751e-01, 9.11147544593241404e-02, -3.27015160605852728e-02};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_5[] = {
    8.91203146812140530e-03, -5.11007903657666879e-02, 1.33065042514096843e-01, -2.10691175441184875e-01,
    2.29212995551205168e-01, -1.80252043861282379e-01, 1.04575528234663068e-01, -5.07250218565727107e-02,
    2.42306613026016422e-02, -7.23016083106520647e-03};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_6[] = {
    4.99486657775736163e-03, -3.21373710699190476e-02, 9.50647736659427506e-02, -1.72407740212183219e-01,
    2.15841213555762024e-01, -1.99626341515829142e-01, 1.42738674019386141e-01, -8.05357220823958997e-02,
    3.59175187598478329e-02, -1.38742313777577616e-02, 5.44279026571374905e-03, -1.41856144133320396e-03};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_7[] = {
    1.56967399528195792e-03, -1.22909118204044543e-02, 4.49552845160746672e-02, -1.02448121259333974e-01,
    1.63756462055961061e-01, -1.95890703309489322e-01, 1.82766482185317769e-01, -1.37439013362758711e-01,
    8.55880560604187907e-02, -4.40516353163853402e-02, 1.83303689208363305e-02, -7.05518401123043752e-03,
    3.03364676863889481e-03, -8.24425417955647680e-04};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_8[] = {
    8.79769531890064408e-04, -7.50346593081252858e-03, 3.00720764201056652e-02, -7.55241504646798345e-02,
    1.33773336933155546e-01, -1.78387869332855276e-01, 1.86733416066399122e-01, -1.57943219649359284e-01,
    1.10270705404717784e-01, -6.47822764929656958e-02, 3.26103689837094757e-02, -1.40180231659652564e-02,
    5.02321627847738660e-03, -1.68288801875860600e-03, 6.37109256876428509e-04, -1.58106717175056409e-04};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_9[] = {
    2.76326171607464374e-04, -2.74290574995829980e-03, 1.29121875546715000e-02, -3.84395392835679695e-02,
    8.14361009396698393e-02, -1.31013844473427010e-01, 1.66817527234382618e-01, -1.73051670990193585e-01,
    1.49446338663523359e-01, -1.09167883917487649e-01, 6.82884799921246594e-02, -3.71438896383521414e-02,
    1.78673498742155969e-02, -7.46145521239084761e-03, 2.58508389106426031e-03, -8.83162700040421842e-04,
    3.70605498405958194e-04, -9.56479956719217021e-05};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_10[] = {
    1.54852720771869842e-04, -1.64534206722766023e-03, 8.32102981560023554e-03, -2.67090538256101462e-02,
    6.12280598179089294e-02, -1.06962424027702480e-01, 1.48392401578966132e-01, -1.68249763083702375e-01,
    1.59283854508077888e-01, -1.28030652040046655e-01, 8.84510344925368147e-02, -5.30188998740236603e-02,
    2.79890435612546347e-02, -1.32444364799451948e-02, 5.46541271233928934e-03, -1.85662637833486225e-03,
    6.40162613758207670e-04, -2.82802151817846076e-04, 7.41481629260780877e-05};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_11[] = {
    4.86264973615752966e-05, -5.84641033936986795e-04, 3.36574059681582277e-03, -1.23711991147361314e-02,
    3.26662072543045523e-02, -6.61103296119098516e-02, 1.06852856029330714e-01, -1.41922679912396210e-01,
    1.58204473840308724e-01, -1.50430877919325218e-01, 1.23603610238367481e-01, -8.87145486478330553e-02,
    5.61327540452923116e-02, -3.15217388471871057e-02, 1.57879335169683020e-02, -7.13679341893215524e-03,
    2.95990417586200916e-03, -1.09006576535600522e-03, 3.32852423984818300e-04, -1.05875503156490172e-04,
    4.50413800996483278e-05, -1.12502249485618536e-05};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_12[] = {
    2.72480048038037585e-05, -3.46652258045090640e-04, 2.11690682709517230e-03, -8.27405124054090765e-03,
    2.32889031054351846e-02, -5.03623983070625725e-02, 8.71828207879123684e-02, -1.24307196129794087e-01,
    1.49081991892961480e-01, -1.52843884919624751e-01, 1.35691367718960343e-01, -1.05416098955378304e-01,
    7.23184199280030859e-02, -4.41572478606217164e-02, 2.41239087164536493e-02, -1.18333468600312422e-02,
    5.28032093333203733e-03, -2.18371665748135326e-03, 8.01779795835931954e-04, -2.40591371459076593e-04,
    7.75069725845497207e-05, -3.48154394387783188e-05, 8.82531650640820420e-06};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_2[] = {8.96381467338864951e-02, -2.57182183283078958e-01,
                                                           3.17288970308536367e-01, -2.41196782850746916e-01,
                                                           9.27549072282227577e-02};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_3[] = {5.09815427800193316e-02, -1.84031646905249174e-01,
                                                           2.75837970519588749e-01, -2.51598622358623292e-01,
                                                           1.72591084616892460e-01, -6.42423032140182620e-02};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_4[] = {
    1.58081037559418582e-02, -8.00181112755787155e-02, 1.83069081452299498e-01, -2.44402088446964344e-01,
    2.09928540281145243e-01, -1.42859005708558751e-01, 9.11147544593241404e-02, -3.27015160605852728e-02};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_5[] = {
    8.91203146812140530e-03, -5.11007903657666879e-02, 1.33065042514096843e-01, -2.10691175441184875e-01,
    2.29212995551205168e-01, -1.80252043861282379e-01, 1.04575528234663068e-01, -5.07250218565727107e-02,
    2.42306613026016422e-02, -7.23016083106520647e-03};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_6[] = {
    4.99486657775736163e-03, -3.21373710699190476e-02, 9.50647736659427506e-02, -1.72407740212183219e-01,
    2.15841213555762024e-01, -1.99626341515829142e-01, 1.42738674019386141e-01, -8.05357220823958997e-02,
    3.59175187598478329e-02, -1.38742313777577616e-02, 5.44279026571374905e-03, -1.41856144133320396e-03};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_7[] = {
    1.56967399528195792e-03, -1.22909118204044543e-02, 4.49552845160746672e-02, -1.02448121259333974e-01,
    1.63756462055961061e-01, -1.95890703309489322e-01, 1.82766482185317769e-01, -1.37439013362758711e-01,
    8.55880560604187907e-02, -4.40516353163853402e-02, 1.83303689208363305e-02, -7.05518401123043752e-03,
    3.03364676863889481e-03, -8.24425417955647680e-04};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_8[] = {
    8.79769531890064408e-04, -7.50346593081252858e-03, 3.00720764201056652e-02, -7.55241504646798345e-02,
    1.33773336933155546e-01, -1.78387869332855276e-01, 1.86733416066399122e-01, -1.57943219649359284e-01,
    1.10270705404717784e-01, -6.47822764929656958e-02, 3.26103689837094757e-02, -1.40180231659652564e-02,
    5.02321627847738660e-03, -1.68288801875860600e-03, 6.37109256876428509e-04, -1.58106717175056409e-04};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_9[] = {
    2.76326171607464374e-04, -2.74290574995829980e-03, 1.29121875546715000e-02, -3.84395392835679695e-02,
    8.14361009396698393e-02, -1.31013844473427010e-01, 1.66817527234382618e-01, -1.73051670990193585e-01,
    1.49446338663523359e-01, -1.09167883917487649e-01, 6.82884799921246594e-02, -3.71438896383521414e-02,
    1.78673498742155969e-02, -7.46145521239084761e-03, 2.58508389106426031e-03, -8.83162700040421842e-04,
    3.70605498405958194e-04, -9.56479956719217021e-05};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_10[] = {
    1.54852720771869842e-04, -1.64534206722766023e-03, 8.32102981560023554e-03, -2.67090538256101462e-02,
    6.12280598179089294e-02, -1.06962424027702480e-01, 1.48392401578966132e-01, -1.68249763083702375e-01,
    1.59283854508077888e-01, -1.28030652040046655e-01, 8.84510344925368147e-02, -5.30188998740236603e-02,
    2.79890435612546347e-02, -1.32444364799451948e-02, 5.46541271233928934e-03, -1.85662637833486225e-03,
    6.40162613758207670e-04, -2.82802151817846076e-04, 7.41481629260780877e-05};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_11[] = {
    4.86264973615752966e-05, -5.84641033936986795e-04, 3.36574059681582277e-03, -1.23711991147361314e-02,
    3.26662072543045523e-02, -6.61103296119098516e-02, 1.06852856029330714e-01, -1.41922679912396210e-01,
    1.58204473840308724e-01, -1.50430877919325218e-01, 1.23603610238367481e-01, -8.87145486478330553e-02,
    5.61327540452923116e-02, -3.15217388471871057e-02, 1.57879335169683020e-02, -7.13679341893215524e-03,
    2.95990417586200916e-03, -1.09006576535600522e-03, 3.32852423984818300e-04, -1.05875503156490172e-04,
    4.50413800996483278e-05, -1.12502249485618536e-05};

// beta: 0
constexpr double esp_sqrt_laplace_3d_potential_grad_12[] = {
    2.72480048038037585e-05, -3.46652258045090640e-04, 2.11690682709517230e-03, -8.27405124054090765e-03,
    2.32889031054351846e-02, -5.03623983070625725e-02, 8.71828207879123684e-02, -1.24307196129794087e-01,
    1.49081991892961480e-01, -1.52843884919624751e-01, 1.35691367718960343e-01, -1.05416098955378304e-01,
    7.23184199280030859e-02, -4.41572478606217164e-02, 2.41239087164536493e-02, -1.18333468600312422e-02,
    5.28032093333203733e-03, -2.18371665748135326e-03, 8.01779795835931954e-04, -2.40591371459076593e-04,
    7.75069725845497207e-05, -3.48154394387783188e-05, 8.82531650640820420e-06};

template <class Real, int MaxVecLen>
residual_evaluator_func<Real> get_esp_sqrt_laplace_3d_kernel(dmk_eval_type eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (eval_level == DMK_POTENTIAL) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 5;
            constexpr int NC0 = 5;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 6;
            constexpr int NC0 = 6;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 8;
            constexpr int NC0 = 8;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 10;
            constexpr int NC0 = 10;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 12;
            constexpr int NC0 = 12;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 14;
            constexpr int NC0 = 14;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 16;
            constexpr int NC0 = 16;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 18;
            constexpr int NC0 = 18;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 19;
            constexpr int NC0 = 19;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 22;
            constexpr int NC0 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 23;
            constexpr int NC0 = 23;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    } else if (eval_level == DMK_POTENTIAL_GRAD) {
        if (n_digits <= 2) {
            constexpr int ND = 2, NC_TOTAL = 5;
            constexpr int NC0 = 5;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_2, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 3) {
            constexpr int ND = 3, NC_TOTAL = 6;
            constexpr int NC0 = 6;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_3, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 4) {
            constexpr int ND = 4, NC_TOTAL = 8;
            constexpr int NC0 = 8;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_4, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 5) {
            constexpr int ND = 5, NC_TOTAL = 10;
            constexpr int NC0 = 10;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_5, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 6) {
            constexpr int ND = 6, NC_TOTAL = 12;
            constexpr int NC0 = 12;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_6, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 7) {
            constexpr int ND = 7, NC_TOTAL = 14;
            constexpr int NC0 = 14;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_7, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 8) {
            constexpr int ND = 8, NC_TOTAL = 16;
            constexpr int NC0 = 16;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_8, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 9) {
            constexpr int ND = 9, NC_TOTAL = 18;
            constexpr int NC0 = 18;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_9, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 10) {
            constexpr int ND = 10, NC_TOTAL = 19;
            constexpr int NC0 = 19;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_10, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 11) {
            constexpr int ND = 11, NC_TOTAL = 22;
            constexpr int NC0 = 22;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_11, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
        if (n_digits <= 12) {
            constexpr int ND = 12, NC_TOTAL = 23;
            constexpr int NC0 = 23;
            std::array<Real, NC_TOTAL> coeffs;
            std::copy_n(esp_sqrt_laplace_3d_potential_grad_12, NC_TOTAL, coeffs.data());
            return [=](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src, const Real *charge,
                       const Real *normals, int n_trg, const Real *r_trg, Real *pot) {
                sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC0, DMK_POTENTIAL_GRAD>(
                    eval_level, ND, rsc, cen, d2max, thresh2, NC0, coeffs.data(), n_src, r_src, charge, normals, n_trg,
                    r_trg, pot, UF);
            };
        }
    }
    throw std::runtime_error("Unsupported eval_level/n_digits combination");
}

// Explicit instantiations
template residual_evaluator_func<float>
get_esp_sqrt_laplace_3d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_eval_type, int);
template residual_evaluator_func<double>
get_esp_sqrt_laplace_3d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_eval_type, int);

} // namespace dmk
