// generate_aot_kernels.cpp
//
// Builds and runs as part of the build process. Generates aot_kernels.cpp
// with all coefficient tables and kernel dispatch functions.
//
// Usage: ./generate_aot_kernels > src/aot_kernels.cpp

#include <dmk.h>
#include <dmk/direct.hpp>
#include <dmk/util.hpp>
#include <format>
#include <iostream>
#include <string>
#include <vector>

struct KernelDef {
    dmk_ikernel kernel;
    std::string kernel_enum;
    int dim;
    std::string func_name;
    std::string getter_name;
};

static const std::vector<KernelDef> all_kernels = {
    {DMK_LAPLACE, "DMK_LAPLACE", 2, "laplace_2d_poly_all_pairs", "get_laplace_2d_kernel"},
    {DMK_LAPLACE, "DMK_LAPLACE", 3, "laplace_3d_poly_all_pairs", "get_laplace_3d_kernel"},
    {DMK_SQRT_LAPLACE, "DMK_SQRT_LAPLACE", 2, "sqrt_laplace_2d_poly_all_pairs", "get_sqrt_laplace_2d_kernel"},
    {DMK_SQRT_LAPLACE, "DMK_SQRT_LAPLACE", 3, "sqrt_laplace_3d_poly_all_pairs", "get_sqrt_laplace_3d_kernel"},
    // {DMK_STOKES, "DMK_STOKES", 2, "stokeslet_2d_poly_all_pairs", "get_stokeslet_2d_kernel"},
    {DMK_STOKESLET, "DMK_STOKESLET", 3, "stokeslet_3d_poly_all_pairs", "get_stokeslet_3d_kernel"},
};

constexpr int min_digits = 2;
constexpr int max_digits = 12;

struct CoeffsInfo {
    int digits;
    double beta;
    std::vector<size_t> sub_sizes; // size of each sub-array
    size_t total_size;             // sum of sub_sizes
};

void emit_coeffs_array(const std::string &name, const std::vector<std::vector<double>> &coeffs, double beta) {
    std::cout << std::format("// beta: {}\n", beta);
    std::cout << std::format("constexpr double {}[] = {{", name);
    int count = 0;
    for (const auto &cvec : coeffs) {
        for (size_t i = 0; i < cvec.size(); ++i) {
            if (count > 0)
                std::cout << ",";
            if (count % 4 == 0)
                std::cout << "\n    ";
            std::cout << std::format(" {:.17e}", cvec[i]);
            count++;
        }
    }
    std::cout << "\n};\n\n";
}

std::string coeff_name(const KernelDef &k, int digits) {
    return std::format(
        "{}_{}d_{}",
        [&] {
            switch (k.kernel) {
            case DMK_LAPLACE:
                return "laplace";
            case DMK_SQRT_LAPLACE:
                return "sqrt_laplace";
            case DMK_STOKESLET:
                return "stokeslet";
            default:
                return "unknown";
            }
        }(),
        k.dim, digits);
}

void emit_getter(const KernelDef &k, const std::vector<CoeffsInfo> &infos) {
    std::cout << std::format(R"(
template <class Real, int MaxVecLen>
residual_evaluator_func<Real> {}(dmk_eval_type eval_level, int n_digits) {{
    constexpr int UF = unroll_factor;
)",
                             k.getter_name);

    for (const auto &info : infos) {
        auto cn = coeff_name(k, info.digits);

        // Build the n_coeffs_rt template args string
        // e.g. for 1 sub-array: "NC0"
        // for 2 sub-arrays: "NC0, NC1"
        std::string nc_decls, nc_args;
        for (size_t i = 0; i < info.sub_sizes.size(); ++i) {
            if (i > 0) {
                nc_decls += "\n";
                nc_args += ", ";
            }
            nc_decls += std::format("        constexpr int NC{} = {};", i, info.sub_sizes[i]);
            nc_args += std::format("NC{}", i);
        }

        std::cout << std::format("    if (n_digits <= {}) {{\n"
                                 "        constexpr int ND = {}, NC_TOTAL = {};\n"
                                 "{}\n"
                                 "        std::array<Real, NC_TOTAL> coeffs;\n"
                                 "        std::copy_n({}, NC_TOTAL, coeffs.data());\n"
                                 "        return [=](Real rsc, Real cen, Real d2max, Real thresh2,\n"
                                 "                   int n_src, const Real *r_src, const Real *charge,\n"
                                 "                   int n_trg, const Real *r_trg, Real *pot) {{\n"
                                 "            {}<Real, MaxVecLen, ND, {}>(\n"
                                 "                eval_level, ND, rsc, cen, d2max, thresh2, {},\n"
                                 "                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);\n"
                                 "        }};\n"
                                 "    }}\n",
                                 info.digits, info.digits, info.total_size, nc_decls, cn, k.func_name, nc_args,
                                 nc_args);
    }

    std::cout << std::format("    throw std::runtime_error(\"Unsupported n_digits: \" + std::to_string(n_digits));\n"
                             "}}\n");
}

int main() {
    std::cout << R"(// Auto-generated by generate_aot_kernels. Do not edit.
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>

namespace dmk {
constexpr int unroll_factor = 3;

)";

    for (auto &k : all_kernels) {
        std::vector<CoeffsInfo> infos;

        for (int digits = min_digits; digits <= max_digits; ++digits) {
            try {
                pdmk_params p;
                p.kernel = k.kernel;
                p.n_dim = k.dim;
                p.eps = std::pow(10, -digits);
                p.debug_flags = 0;
                const double beta = dmk::util::calc_bandlimiting(p);
                const auto coeffs = dmk::get_local_correction_coeffs<double>(k.kernel, k.dim, digits, beta);

                CoeffsInfo info;
                info.digits = digits;
                info.beta = beta;
                info.total_size = 0;
                for (const auto &cvec : coeffs) {
                    info.sub_sizes.push_back(cvec.size());
                    info.total_size += cvec.size();
                }

                emit_coeffs_array(coeff_name(k, digits), coeffs, beta);
                infos.push_back(std::move(info));
            } catch (std::exception &e) {
                std::cerr << std::format("// Skipped {} digits={}: {}\n", k.getter_name, digits, e.what());
            }
        }

        emit_getter(k, infos);
    }

    // Emit explicit instantiations
    std::cout << "\n// Explicit instantiations\n";
    for (auto &k : all_kernels) {
        for (auto type : {"float", "double"}) {
            std::cout << std::format("template residual_evaluator_func<{0}>\n"
                                     "{1}<{0}, sctl::DefaultVecLen<{0}>()>(dmk_eval_type, int);\n",
                                     type, k.getter_name);
        }
    }

    std::cout << "\n} // namespace dmk\n";

    return 0;
}
