import re

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src/aot_kernels.cpp")
OUT = os.path.join(ROOT, "include/dmk/cuda/esp_sr_coeffs.cuh")

with open(SRC) as f:
    text = f.read()

expected_counts = {2: 5, 3: 6, 4: 9, 5: 11, 6: 13, 7: 16, 8: 17, 9: 20, 10: 22, 11: 25, 12: 27}

def extract(name):
    m = re.search(r"constexpr double " + re.escape(name) + r"\[\]\s*=\s*\{(.*?)\};", text, re.S)
    if not m:
        raise RuntimeError("array not found: " + name)
    body = m.group(1)
    toks = [t.strip() for t in body.split(",")]
    toks = [t for t in toks if t]
    return toks

def emit(out, tag_name, tokens, nd):
    if len(tokens) != expected_counts[nd]:
        raise RuntimeError("count mismatch for %s: got %d expected %d" % (tag_name, len(tokens), expected_counts[nd]))
    out.append("struct %s {" % tag_name)
    out.append("    using value_type = double;")
    out.append("    static constexpr std::size_t size = %d;" % len(tokens))
    out.append("    static constexpr double at(std::size_t i) {")
    out.append("        switch (i) {")
    for i, t in enumerate(tokens):
        out.append("        case %d: return %s;" % (i, t))
    out.append("        default: return 0.0;")
    out.append("        }")
    out.append("    }")
    out.append("};")
    out.append("")

lines = []
lines.append("// Auto-generated by scripts/generate_esp_sr_coefftags.py from aot_kernels.cpp's")
lines.append("// esp_3d_potential(_grad)_N tables. Do not edit by hand -- regenerate if those change.")
lines.append("//")
lines.append("// Compile-time CoeffTag wrappers (see CoeffTag concept in esp_cuda.cu) around")
lines.append("// the same monomial fit tables get_esp_3d_kernel (aot_kernels.cpp) dispatches")
lines.append("// into on the CPU path -- literal values here are verbatim copies of those")
lines.append("// decimal literals (same text -> same IEEE-754 double under any conforming")
lines.append("// compiler), not a re-fit.")
lines.append("#pragma once")
lines.append("")
lines.append("#include <cstddef>")
lines.append("")
lines.append("namespace dmk {")
lines.append("")

for nd in range(2, 13):
    toks = extract("esp_3d_potential_%d" % nd)
    emit(lines, "EspSrCoeffs_Pot_%d" % nd, toks, nd)

for nd in range(2, 13):
    toks = extract("esp_3d_potential_grad_%d" % nd)
    emit(lines, "EspSrCoeffs_PotGrad_%d" % nd, toks, nd)

lines.append("} // namespace dmk")
lines.append("")

with open(OUT, "w") as f:
    f.write("\n".join(lines))

print("wrote", OUT, "(%d lines)" % len(lines))
