// generate_aot_kernels.cpp
//
// Builds and runs as part of the build process. Generates aot_kernels.cpp
// with all coefficient tables and kernel dispatch functions.
//
// Usage: ./generate_aot_kernels > src/aot_kernels.cpp

#include <dmk.h>
#include <dmk/direct.hpp>
#include <format>
#include <iostream>
#include <string>
#include <vector>

struct KernelDef {
    dmk_ikernel kernel;
    std::string kernel_enum;   // e.g. "DMK_LAPLACE"
    int dim;
    std::string func_name;     // e.g. "laplace_3d_poly_all_pairs"
    std::string getter_name;   // e.g. "get_laplace_3d_kernel"
};

static const std::vector<KernelDef> all_kernels = {
    {DMK_LAPLACE, "DMK_LAPLACE", 2, "laplace_2d_poly_all_pairs", "get_laplace_2d_kernel"},
    {DMK_LAPLACE, "DMK_LAPLACE", 3, "laplace_3d_poly_all_pairs", "get_laplace_3d_kernel"},
    {DMK_SQRT_LAPLACE, "DMK_SQRT_LAPLACE", 2, "sqrt_laplace_2d_poly_all_pairs", "get_sqrt_laplace_2d_kernel"},
    {DMK_SQRT_LAPLACE, "DMK_SQRT_LAPLACE", 3, "sqrt_laplace_3d_poly_all_pairs", "get_sqrt_laplace_3d_kernel"},
};

constexpr int min_digits = 3;
constexpr int max_digits = 12;

void emit_coeffs_array(const std::string &name, const std::vector<double> &c) {
    std::cout << std::format("constexpr double {}[] = {{", name);
    for (size_t i = 0; i < c.size(); ++i) {
        if (i > 0) std::cout << ",";
        if (i % 4 == 0) std::cout << "\n    ";
        std::cout << std::format(" {:.17e}", c[i]);
    }
    std::cout << "\n};\n\n";
}

std::string coeff_name(const KernelDef &k, int digits) {
    return std::format("{}_{}d_{}", [&] {
        switch (k.kernel) {
        case DMK_LAPLACE: return "laplace";
        case DMK_SQRT_LAPLACE: return "sqrt_laplace";
        default: return "unknown";
        }
    }(), k.dim, digits);
}

void emit_getter(const KernelDef &k,
                 const std::vector<std::pair<int, size_t>> &digit_sizes) {
    std::cout << std::format(R"(
template <class Real, int MaxVecLen>
direct_evaluator_func<Real> {}(dmk_pgh eval_level, int n_digits) {{
    constexpr int UF = unroll_factor;
)",
        k.getter_name);

    for (auto &[digits, nc] : digit_sizes) {
        auto cn = coeff_name(k, digits);
        std::cout << std::format(
            "    if (n_digits <= {}) {{\n"
            "        constexpr int ND = {}, NC = {};\n"
            "        std::array<Real, NC> coeffs;\n"
            "        std::copy_n({}, NC, coeffs.data());\n"
            "        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2,\n"
            "                                    int n_src, const Real *r_src, const Real *charge,\n"
            "                                    int n_trg, const Real *r_trg, Real *pot) {{\n"
            "            {}<Real, MaxVecLen, ND, NC>(\n"
            "                eval_level, ND, rsc, cen, d2max, thresh2, NC,\n"
            "                coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot, UF);\n"
            "        }};\n"
            "    }}\n",
            digits, digits, nc, cn, k.func_name);
    }

    std::cout << std::format(
        "    throw std::runtime_error(\"Unsupported n_digits: \" + std::to_string(n_digits));\n"
        "}}\n");
}

int main() {
    std::cout << R"(// Auto-generated by generate_aot_kernels. Do not edit.
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>

namespace dmk {
constexpr int unroll_factor = 3;

)";

    // For each kernel/dim, compute coefficients for all digit counts and emit
    for (auto &k : all_kernels) {
        std::vector<std::pair<int, size_t>> digit_sizes;

        for (int digits = min_digits; digits <= max_digits; ++digits) {
            try {
                auto coeffs = dmk::get_local_correction_coeffs<double>(k.kernel, k.dim, digits);
                emit_coeffs_array(coeff_name(k, digits), coeffs);
                digit_sizes.emplace_back(digits, coeffs.size());
            } catch (std::exception &e) {
                std::cerr << std::format("// Skipped {} digits={}: {}\n",
                                         k.getter_name, digits, e.what());
            }
        }

        emit_getter(k, digit_sizes);
    }

    // Emit explicit instantiations
    std::cout << "\n// Explicit instantiations\n";
    for (auto &k : all_kernels) {
        for (auto type : {"float", "double"}) {
            std::cout << std::format(
                "template direct_evaluator_func<{0}>\n"
                "{1}<{0}, sctl::DefaultVecLen<{0}>()>(dmk_pgh, int);\n",
                type, k.getter_name);
        }
    }

    std::cout << "\n} // namespace dmk\n";

    return 0;
}
