pipeline {
    agent none
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
        timeout(time: 1, unit: 'HOURS')
    }
    stages {
        stage('main') {
            agent {
                dockerfile {
                    dir 'ci'
                }
            }
            environment {
                HOME = "${WORKSPACE}"
                LC_ALL = "C"
                OMP_NUM_THREADS = "2"
            }
            steps {
                sh 'which mpicxx'
                sh 'git submodule update --init --recursive'
                sh 'CXX=mpicxx F90=mpif90 cmake -B build . -DCMAKE_BUILD_TYPE=Release'
                sh 'cd build && make -j4'
                sh 'mpirun -n 1 ./build/test/test_all -tc="*pdmk*"'
                sh 'mpirun -n 2 ./build/test/test_all -tce="*pdmk*"'
            }
        }
    }
    post {
        failure {
            emailext subject: '$PROJECT_NAME - Build #$BUILD_NUMBER - $BUILD_STATUS',
	        body: '''$PROJECT_NAME - Build #$BUILD_NUMBER - $BUILD_STATUS
Check console output at $BUILD_URL to view full results.
Building $BRANCH_NAME for $CAUSE
$JOB_DESCRIPTION
Changes:
$CHANGES
End of build log:
${BUILD_LOG,maxLines=200}
''',
	        recipientProviders: [
		[$class: 'DevelopersRecipientProvider'],
	    ],
	        replyTo: '$DEFAULT_REPLYTO',
	        to: 'rblackwell@flatironinstitute.org'
        }
    }
}
