properties([
  disableConcurrentBuilds(),
  buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
])

try {
  timeout(time: 1, unit: 'HOURS') {
    buildPod(context: 'ci') {
      stage('main') {
        withEnv([
          "HOME=${WORKSPACE}",
          "LC_ALL=C",
          "OMP_NUM_THREADS=2",
          "OPENBLAS_NUM_THREADS=1"
        ]) {
          sh 'which mpicxx'
          sh 'git submodule update --init --recursive'
          sh 'cmake -B build . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/build/install -DCMAKE_CXX_COMPILER=g++'
          sh 'cd build && make -j$PARALLEL'
          sh 'mpirun -n 2 --bind-to none ./build/test/test_all -nc'
        }
      }
    }
  }
}
finally {
  emailFailure()
}
