// Auto-generated by generate_aot_kernels. Do not edit.
#include <dmk.h>
#include <dmk/types.hpp>
#include <dmk/vector_kernels.hpp>
#include <sctl.hpp>

namespace dmk {
constexpr int unroll_factor = 3;

constexpr double laplace_2d_3[] = {2.56024812373876753e-01, -2.86702855259382383e-01, 3.07894905345502921e-02,
                                   -1.25486877787345393e-03, 1.27010819658795869e-05};

constexpr double laplace_2d_4[] = {2.88758533072985601e-01,  -3.11459796970033953e-01, 4.24422982971522714e-02,
                                   -4.48267314627199924e-03, 4.76961773545513318e-04,  -3.86719758958271509e-05,
                                   2.18952855337290719e-06,  -8.87477165744858529e-08};

constexpr double laplace_2d_5[] = {2.99604586561240727e-01,  -3.73739552444638523e-01, 9.15453471236191280e-02,
                                   -1.93459685782132185e-02, 2.81901597177355726e-03,  -2.65777593962264274e-04,
                                   1.71600060879454740e-05,  -8.04847669765972978e-07, 2.87030370588980961e-08,
                                   -8.00136636465699724e-10};

constexpr double laplace_2d_6[] = {
    3.19490369732046919e-01,  -4.08182167789759742e-01, 1.06491147423631985e-01, -2.09670023258909238e-02,
    2.50182289824305536e-03,  -1.60904788729735457e-04, 3.96966798563163723e-06, 1.74454746020107835e-07,
    -1.82883278739935325e-08, 5.85094275803735120e-10,  6.67600859211026297e-11, -1.51975718795580670e-11,
    -1.11094660666468327e-10, 3.38448533845934895e-11,  1.30790163316386909e-10, -6.65585366135778104e-11,
    -9.72716462644391703e-11, 7.76407254111542736e-11,  4.19339275731754599e-11, -4.70851055236950064e-11,
    -8.02127609152222438e-12, 1.14980502595395408e-11};

constexpr double laplace_2d_7[] = {};

constexpr double laplace_2d_8[] = {};

constexpr double laplace_2d_9[] = {};

constexpr double laplace_2d_10[] = {};

constexpr double laplace_2d_11[] = {};

constexpr double laplace_2d_12[] = {};

template <class Real, int MaxVecLen>
direct_evaluator_func<Real> get_laplace_2d_kernel(dmk_pgh eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (n_digits <= 3) {
        constexpr int ND = 3, NC = 5;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_3, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 4) {
        constexpr int ND = 4, NC = 8;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_4, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 5) {
        constexpr int ND = 5, NC = 10;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_5, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 6) {
        constexpr int ND = 6, NC = 22;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_6, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 7) {
        constexpr int ND = 7, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_7, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 8) {
        constexpr int ND = 8, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_8, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 9) {
        constexpr int ND = 9, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_9, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 10) {
        constexpr int ND = 10, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_10, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 11) {
        constexpr int ND = 11, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_11, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 12) {
        constexpr int ND = 12, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_2d_12, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    throw std::runtime_error("Unsupported n_digits: " + std::to_string(n_digits));
}
constexpr double laplace_3d_3[] = {3.59352216489611631e-01, -5.29577278216261438e-01, 1.53806289663060758e-01,
                                   3.08165315377173302e-02, -1.37719559094845907e-02, -1.23978813303763291e-03,
                                   6.13723204886006861e-04};

constexpr double laplace_3d_4[] = {2.97080935255406964e-01, -5.26801212015735598e-01, 2.31920432432083989e-01,
                                   2.73070147423109255e-02, -3.12129164069161781e-02, -4.69342348666627939e-04,
                                   2.31676035861803518e-03, -3.92836098975129014e-05, -1.08495795458931577e-04,
                                   2.82333457398634539e-06, 3.28423123826049806e-06};

constexpr double laplace_3d_5[] = {2.45448106458190041e-01,  -5.12409643370177470e-01, 3.01787776619231174e-01,
                                   8.56751810725959496e-03,  -5.21122086690222475e-02, 4.42825429099041185e-03,
                                   5.20118992350946177e-03,  -6.29028086426284432e-04, -3.40009470824352220e-04,
                                   4.49144087995459966e-05,  1.56655123863595172e-05,  -2.07862230105843786e-06,
                                   -5.33363799291477824e-07, 6.32719527538486660e-08,  1.29903451790538712e-08};

constexpr double laplace_3d_6[] = {};

constexpr double laplace_3d_7[] = {};

constexpr double laplace_3d_8[] = {};

constexpr double laplace_3d_9[] = {};

constexpr double laplace_3d_10[] = {};

constexpr double laplace_3d_11[] = {};

constexpr double laplace_3d_12[] = {};

template <class Real, int MaxVecLen>
direct_evaluator_func<Real> get_laplace_3d_kernel(dmk_pgh eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (n_digits <= 3) {
        constexpr int ND = 3, NC = 7;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_3, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 4) {
        constexpr int ND = 4, NC = 11;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_4, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 5) {
        constexpr int ND = 5, NC = 15;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_5, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 6) {
        constexpr int ND = 6, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_6, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 7) {
        constexpr int ND = 7, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_7, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 8) {
        constexpr int ND = 8, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_8, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 9) {
        constexpr int ND = 9, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_9, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 10) {
        constexpr int ND = 10, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_10, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 11) {
        constexpr int ND = 11, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_11, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    if (n_digits <= 12) {
        constexpr int ND = 12, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(laplace_3d_12, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                               coeffs.data(), n_src, r_src, charge, n_trg, r_trg, pot,
                                                               UF);
        };
    }
    throw std::runtime_error("Unsupported n_digits: " + std::to_string(n_digits));
}
constexpr double sqrt_laplace_2d_3[] = {3.59352216489611631e-01, -5.29577278216261438e-01, 1.53806289663060758e-01,
                                        3.08165315377173302e-02, -1.37719559094845907e-02, -1.23978813303763291e-03,
                                        6.13723204886006861e-04};

constexpr double sqrt_laplace_2d_4[] = {2.97080935255406964e-01, -5.26801212015735598e-01, 2.31920432432083989e-01,
                                        2.73070147423109255e-02, -3.12129164069161781e-02, -4.69342348666627939e-04,
                                        2.31676035861803518e-03, -3.92836098975129014e-05, -1.08495795458931577e-04,
                                        2.82333457398634539e-06, 3.28423123826049806e-06};

constexpr double sqrt_laplace_2d_5[] = {2.45448106458190041e-01,  -5.12409643370177470e-01, 3.01787776619231174e-01,
                                        8.56751810725959496e-03,  -5.21122086690222475e-02, 4.42825429099041185e-03,
                                        5.20118992350946177e-03,  -6.29028086426284432e-04, -3.40009470824352220e-04,
                                        4.49144087995459966e-05,  1.56655123863595172e-05,  -2.07862230105843786e-06,
                                        -5.33363799291477824e-07, 6.32719527538486660e-08,  1.29903451790538712e-08};

constexpr double sqrt_laplace_2d_6[] = {};

constexpr double sqrt_laplace_2d_7[] = {};

constexpr double sqrt_laplace_2d_8[] = {};

constexpr double sqrt_laplace_2d_9[] = {};

constexpr double sqrt_laplace_2d_10[] = {};

constexpr double sqrt_laplace_2d_11[] = {};

constexpr double sqrt_laplace_2d_12[] = {};

template <class Real, int MaxVecLen>
direct_evaluator_func<Real> get_sqrt_laplace_2d_kernel(dmk_pgh eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (n_digits <= 3) {
        constexpr int ND = 3, NC = 7;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_3, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 4) {
        constexpr int ND = 4, NC = 11;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_4, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 5) {
        constexpr int ND = 5, NC = 15;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_5, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 6) {
        constexpr int ND = 6, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_6, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 7) {
        constexpr int ND = 7, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_7, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 8) {
        constexpr int ND = 8, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_8, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 9) {
        constexpr int ND = 9, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_9, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 10) {
        constexpr int ND = 10, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_10, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 11) {
        constexpr int ND = 11, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_11, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 12) {
        constexpr int ND = 12, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_2d_12, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_2d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    throw std::runtime_error("Unsupported n_digits: " + std::to_string(n_digits));
}
constexpr double sqrt_laplace_3d_3[] = {3.44667773244710207e-01,  -4.78420518935334216e-01, 1.53666944699530905e-01,
                                        -2.14983752220403689e-02, 1.66519714273249530e-03,  -8.11037704910181815e-05};

constexpr double sqrt_laplace_3d_4[] = {2.68133741640663337e-01,  -4.46979848587826689e-01, 2.24900790279250057e-01,
                                        -5.24327277931292898e-02, 6.93107959843097549e-03,  -5.85952054481205182e-04,
                                        3.43881059317416874e-05,  -1.47155489681260560e-06};

constexpr double sqrt_laplace_3d_5[] = {2.03834919773978496e-01,  -4.04069323857741858e-01, 2.77548567421473324e-01,
                                        -9.35645579732161115e-02, 1.84057472202968954e-02,  -2.35227564595155226e-03,
                                        2.10068789565355719e-04,  -1.38147718785577730e-05, 6.95901913024476640e-07,
                                        -2.77511892862249155e-08, 8.92771954606227010e-10};

constexpr double sqrt_laplace_3d_6[] = {};

constexpr double sqrt_laplace_3d_7[] = {};

constexpr double sqrt_laplace_3d_8[] = {};

constexpr double sqrt_laplace_3d_9[] = {};

constexpr double sqrt_laplace_3d_10[] = {};

constexpr double sqrt_laplace_3d_11[] = {};

constexpr double sqrt_laplace_3d_12[] = {};

template <class Real, int MaxVecLen>
direct_evaluator_func<Real> get_sqrt_laplace_3d_kernel(dmk_pgh eval_level, int n_digits) {
    constexpr int UF = unroll_factor;
    if (n_digits <= 3) {
        constexpr int ND = 3, NC = 6;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_3, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 4) {
        constexpr int ND = 4, NC = 8;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_4, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 5) {
        constexpr int ND = 5, NC = 11;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_5, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 6) {
        constexpr int ND = 6, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_6, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 7) {
        constexpr int ND = 7, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_7, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 8) {
        constexpr int ND = 8, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_8, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 9) {
        constexpr int ND = 9, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_9, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 10) {
        constexpr int ND = 10, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_10, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 11) {
        constexpr int ND = 11, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_11, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    if (n_digits <= 12) {
        constexpr int ND = 12, NC = 0;
        std::array<Real, NC> coeffs;
        std::copy_n(sqrt_laplace_3d_12, NC, coeffs.data());
        return [coeffs, eval_level](Real rsc, Real cen, Real d2max, Real thresh2, int n_src, const Real *r_src,
                                    const Real *charge, int n_trg, const Real *r_trg, Real *pot) {
            sqrt_laplace_3d_poly_all_pairs<Real, MaxVecLen, ND, NC>(eval_level, ND, rsc, cen, d2max, thresh2, NC,
                                                                    coeffs.data(), n_src, r_src, charge, n_trg, r_trg,
                                                                    pot, UF);
        };
    }
    throw std::runtime_error("Unsupported n_digits: " + std::to_string(n_digits));
}

// Explicit instantiations
template direct_evaluator_func<float> get_laplace_2d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_pgh, int);
template direct_evaluator_func<double> get_laplace_2d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_pgh, int);
template direct_evaluator_func<float> get_laplace_3d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_pgh, int);
template direct_evaluator_func<double> get_laplace_3d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_pgh, int);
template direct_evaluator_func<float> get_sqrt_laplace_2d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_pgh, int);
template direct_evaluator_func<double> get_sqrt_laplace_2d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_pgh, int);
template direct_evaluator_func<float> get_sqrt_laplace_3d_kernel<float, sctl::DefaultVecLen<float>()>(dmk_pgh, int);
template direct_evaluator_func<double> get_sqrt_laplace_3d_kernel<double, sctl::DefaultVecLen<double>()>(dmk_pgh, int);

} // namespace dmk
