# Generates a C++ translation unit embedding the CUDA JIT sources and headers as
# raw string literals, so the runtime JIT path does not depend on the source
# tree being present after install.
#
# Inputs (passed via -D on the command line, "|"-separated to survive argument
# splitting):
#   EMBED_OUTPUT   output .cpp path
#   EMBED_CU       "|"-separated list of .cu source file paths
#   EMBED_HEADERS  "|"-separated list of "<include-name>=<file-path>" entries

string(REPLACE "|" ";" cu_sources "${EMBED_CU}")
string(REPLACE "|" ";" header_entries "${EMBED_HEADERS}")

set(out "// Generated by cmake/embed_jit_sources.cmake. Do not edit.\n")
string(APPEND out "#include <string_view>\n")
string(APPEND out "#include <unordered_map>\n\n")
string(APPEND out "namespace dmk::cuda::jit {\n\n")

string(APPEND out "const std::string_view *find_embedded_jit_source(std::string_view filename) {\n")
string(APPEND out "    static const std::unordered_map<std::string_view, std::string_view> sources = {\n")

foreach(path ${cu_sources})
    get_filename_component(name "${path}" NAME)
    # Sources under an evaluator subdirectory (e.g. src/cuda/pt/jit_sources) are
    # keyed as "<subdir>/<name>" so their bare filenames don't collide with the
    # flat V1 sources; V1 sources keep their basename key. EMBED_ROOT is src/cuda.
    file(RELATIVE_PATH rel "${EMBED_ROOT}" "${path}")
    if (rel MATCHES "^([^/]+)/jit_sources/")
        set(key "${CMAKE_MATCH_1}/${name}")
    else()
        set(key "${name}")
    endif()
    file(READ "${path}" contents)
    string(APPEND out "        {\"${key}\", std::string_view(R\"DMKJITSRC(${contents})DMKJITSRC\")},\n")
endforeach()

string(APPEND out "    };\n\n")
string(APPEND out "    auto it = sources.find(filename);\n")
string(APPEND out "    return it == sources.end() ? nullptr : &it->second;\n")
string(APPEND out "}\n\n")

list(LENGTH header_entries n_headers)

string(APPEND out "int embedded_jit_header_count() { return ${n_headers}; }\n\n")

string(APPEND out "const char *embedded_jit_header_name(int i) {\n")
string(APPEND out "    static const char *const names[] = {\n")
foreach(entry ${header_entries})
    string(REGEX MATCH "^[^=]+" hname "${entry}")
    string(APPEND out "        \"${hname}\",\n")
endforeach()
string(APPEND out "    };\n")
string(APPEND out "    return names[i];\n")
string(APPEND out "}\n\n")

string(APPEND out "const char *embedded_jit_header_source(int i) {\n")
string(APPEND out "    static const char *const contents[] = {\n")
foreach(entry ${header_entries})
    string(REGEX REPLACE "^[^=]+=" "" hpath "${entry}")
    file(READ "${hpath}" hcontents)
    string(APPEND out "        R\"DMKJITHDR(${hcontents})DMKJITHDR\",\n")
endforeach()
string(APPEND out "    };\n")
string(APPEND out "    return contents[i];\n")
string(APPEND out "}\n\n")

string(APPEND out "} // namespace dmk::cuda::jit\n")

file(WRITE "${EMBED_OUTPUT}" "${out}")
