#!/bin/sh
set -x

if command -v clang-format >/dev/null 2>&1; then
    for f in $(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|hpp|h|c)$'); do
        clang-format -i "$f"
        git add "$f"
    done
fi
